### ISSUE TITLE
Clicking on the slider without moving it will refresh the ad vault

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#1010]
This is a minor issue, but doesn't it make more sense if the refresh only happens if the slider has been changed?

**Comment by dhowe** [comment]
Indeed. There was originally code for this, though not sure what happened to it. In fact, we want to refresh only a) on slider-release AND b) the selected range is different

**Comment by greysonevins** [comment]
I've been going back and forth on this issue all day. It looks like part of the problem is that the refresh is initialized by a `runFilter(d3.event.target.extent())` which looks like it triggers a `runFliter` when you even exit a selected image. I'm new to do d3 but I am trying to see if we can change the `runFilter` function to happen only if the attribute `transform` for `resize e` and `resize w` are changed.

**Comment by greysonevins** [comment]
This took me a while, but I figured a way to do this was by making the transformation values constant rather than time. @dhowe  @cqx931  55467ad

**Comment by greysonevins** [comment]
@dhowe closed?

**Comment by dhowe** [comment]
@cqx931 please verify

**Comment by cqx931** [comment]
verified
