### ISSUE TITLE
Forbes Ad blocked but not collected

### ISSUE THREAD

**Issue by greysonevins** [dhowe/AdNauseam#1087]
### Describe the issue
Looks like it has a cosmetic filter but is not collected like the Fortune ads we fixed too.
https://www.forbes.com/sites/realspin/2017/06/22/heres-what-a-worker-first-policy-might-look-like-for-the-trump-admin-think-apprenticeships/#2149fd2f85a8

![image](https://user-images.githubusercontent.com/11656811/27490743-72b59d28-580d-11e7-9484-a97ed9a7d9e1.png)

**Comment by greysonevins** [comment]
@dhowe I found that easylist is blocking the revcontent ad I noted above but when I allow the js to run it doesn't seem to appear. Is there something I need to do here?

**Comment by dhowe** [comment]
figure out what is blocking the ad (using the ublock logger), and then add an exception rule to make it show up

**Comment by greysonevins** [comment]
@dhowe so I found what was blocking it and was able to find a way to grab the ads too, but the issue I am seeing now is that the ad is loaded dynamically with an `<a>` tag so the ad parser is not grabbing the image or href.  Any thoughts here?

I used:
```
@@||revcontent.com^$third-party

@@||criteo.net^$third-party


forbes.com#@#.rc-item-wrapper
forbes.com#@##rc-row-container
forbes.com#@#.rc-cta[data-target]

!trying to collect the ads with this!
##.rc-item > .rc-item-wrapper > .rc-cta
```

**Comment by dhowe** [comment]
when the dom changes, the content-script should re-run... is this happening?  is the ad then getting rejected as a duplicate? check the logs...

**Comment by greysonevins** [comment]
<img width="1178" alt="screen shot 2017-07-18 at 7 10 30 pm" src="https://user-images.githubusercontent.com/11656811/28343736-d6fffd12-6bec-11e7-944d-6c359274f3e5.png">

@dhowe you'll see that the ad's photo/link/and title are all mashed into an a tag and dynamically generated by javascript. I don't think there is anything I can do with it like I had hoped.

**Comment by dhowe** [comment]
@cqx931 pls take a look

**Comment by cqx931** [comment]
The a tag is only the link, but the image is inside `<div class="rc-photo-container"></div>` and the ad content is inside `<div class="rc-content"></div>`. 

We can't parse the ad with the current parser due to two reasons:
1. The image is displayed through background image css
![image](https://user-images.githubusercontent.com/3056154/29244296-e0de8d5e-7fb4-11e7-81f3-168a40196437.png)
2.The a tag doesn't wrap around the ad, the link is placed over the ad through css.

**Comment by dhowe** [comment]
Any proposed solution?

**Comment by cqx931** [comment]
If we do want to parse ad like this, we need to first solve the case when image ad is displayed through css "background-image". Please see: https://github.com/dhowe/AdNauseam/issues/451

However, I'm not sure how to solve the second issue. Right now we are checking clickableParent for the image to decide whether it is an ad or not. We can also check other children div within the same parent, but we don't know whether the a tag is a link that is not related to the image, or it is placed above the img later through css. It makes more sense to me if we ignore these cases rather than filter the ad out.

**Comment by dhowe** [comment]
Lets start by adding a test page for this case...

**Comment by cqx931** [comment]
background case solved in https://github.com/dhowe/AdNauseam/commit/be57516cdbefb84026df4b544c8e863e2d9c9247

Can this be closed? @dhowe

**Comment by dhowe** [comment]
yes, assuming we have a test case in our release tests ?
