### ISSUE TITLE
Ad(s) not collected on reuters.com

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1107]
The ad below is NOT visible, but is also not collected

http://www.reuters.com/article/us-cyber-conference-iran-idUSKBN1AC28L

![image](https://user-images.githubusercontent.com/737638/28740169-c4883e48-73cf-11e7-9d9d-9f35e61d1ac8.png)

**Comment by greysonevins** [comment]
@dhowe see PR. Some ads are simply blocked, but most I saw were collected after the fix.

**Comment by greysonevins** [comment]
@dhowe @cqx931 I'm not sure why either, but in my tests of the site--this was the only way to collect the ads. Please test it:

```
reuters.*#@#iframe[id^="google_ads_iframe"]
reuters.*#@#div[id^="google_ads_iframe_"]
reuters.*##div[id^="google_ads_iframe_"]
```

**Comment by cqx931** [comment]
I can't reproduce this case consistently and I can only see the ad 'hidden', but not collected from time to time if I use an VPN from the states.

When the ad is 'hidden' but not collected, what I can observe is that the ad is not rendered in the google iframe. This could be related if the script doesn't load the image if the iframe/div is not visible.  Therefore it makes sense to me if we unhidden the google_ads_iframe iframe and div, and hide the outer div `reuters.*##.CanvasAd_container_sZDIL` instead.

```
 reuters.com#@#iframe[id^="google_ads_iframe"]
 reuters.com#@#div[id^="google_ads_iframe_"]
 reuters.com##.CanvasAd_container_sZDIL
```
<hr>
Now let's get back to what you added @greysonevins .
It would be nice if you could explain more about your reason why you write the following rules, so that I can understand your logic behind. From my testing and guessing, there are a few points that I want to mention about your rules:
1.
```
reuters.*#@#iframe[id^="google_ads_iframe_"]
reuters.*#@#div[id^="google_ads_iframe_"]
```
In the two rules above, are you trying to make exception rules for reuters? If yes, this is not doing what you expect it to do because the '*' in the domain name.
From my testing, the logger doesn't regard `reuters.*#@#iframe[id^="google_ads_iframe_"]` as an exception rule. Instead it reads it as exactly the same as `reuters.*##iframe[id^="google_ads_iframe_"]`.  However, if I change it to `reuters.com`, it will then regard it as an exception rule and doesn't process the element anymore.  This should be related to the syntax for adblock rules https://adblockplus.org/filters#elemhide_exceptions. Please correct me if I am wrong, but what I understand is that 'reuters.*' is not a proper way to specify the domain for exception rules.

2.Instead of `reuters.*`reuters.com` is already enough for the rule to be applied to the website in other countries. For example, their german website is `de.reuters.com`.

Please let me know if you have any question or if anything above doesn't make sense to you.

**Comment by mneunomne** [comment]
I was able to have ad collection but for the `dianomi.com` sponsored content. But in order to do that I had to allow the third-party scripts coming from it, and another cosmetic rule to hide the general iframe:

```
reuters.com##[src^="https://www.dianomi.com/"]
@@||www.dianomi.com^$domain=reuters.com
```

With these all of them were collected:

![Screen Shot 2021-05-17 at 16 17 25](https://user-images.githubusercontent.com/4967860/118504002-6d4a6180-b72b-11eb-8e1e-98324815f552.png)

**Comment by dhowe** [comment]
nice
