### ISSUE TITLE
Blocked on Pale Moon

### ISSUE THREAD

**Issue by animepony** [dhowe/AdNauseam#1121]
### Describe the issue
Pale Moon's developer, Moonchild productions, has forcibly disabled the AdNauseam extension via a blocklist, classifying it as "malware"

### One or more specific URLs where the issue occurs
Applies to all URLs

### Screenshot in which the issue can be seen
![palemoon-error](https://my.mixtape.moe/qigojk.png)

### Steps for anyone to reproduce the issue
Attempt installing AdNauseum on latest Pale Moon

### Your settings

- OS/version:
Debian Stretch GNU/Linux
- Browser/version:
Pale Moon 27.3.0
- AdNauseam version:
3.3.403
- Other extensions you have installed:
Not applicable.

May I suggest documenting a work-around in the wiki, similar to what we have for Google Chrome.

Hate to see this happen to yet another browser.... :-1:

**Comment by ironsm4sh** [comment]
in palemoon's about:config, you can work around the issue.
not a solution though.

**Comment by animepony** [comment]
Expanding on ironsm4sh's comment:

https://forum.palemoon.org/viewtopic.php?f=46&t=16504&p=120322&hilit=adnauseam#p120322

Setting `extensions.blocklist.level` to 3 will allow you to continue using the extension. This should be sufficient for a wiki entry... at least for the workaround.

**Comment by nukeop** [comment]
Remember to visit palemoon's website every day with AdNauseam on to be up to date on this issue. Preferably refresh every 5 minutes too.

**Comment by corysimmons** [comment]
>Your browser, Y**our** way

**Comment by dhowe** [comment]
Anyone know where (or from who) we can get more info on this decision ?

**Comment by greysonevins** [comment]
see @animepony's link above
https://forum.palemoon.org/viewtopic.php?f=46&t=16504&p=120322&hilit=adnauseam#p120322 
"Since proponents of this extension will likely be unhappy or have questions as to why, and likely want to be vocal about this addition:

After investigating the AdNauseam extension's behavior and the results for web publishers, the extension has been added to the Pale Moon blocklist with a severity level of 2 (meaning you won't be able to enable it unless you increase the blocking level in about:config to 3). For those unfamiliar with this extension: it generates false ad "clicks" to ad servers in an attempt to generate "noise" for the ad networks in a protest against the advertising network system as a whole.
While the premise behind this is similar to poisoning trackers with false fingerprints (which we are proponents of, ourselves), and we normally let users decide for themselves what they want to do with their browser, we are strictly against allowing extensions that cause direct damage (including damage to third parties). There is a subtle but important difference between blocking content and generating fake user interaction.

As such, this decision to block was made because of the following reasons:
- Generating fake clicks on ads will flag publisher accounts with "invalid traffic". If this kind of traffic persists, it causes damage for the website owners who run ads:
     - One facet of damage caused is direct devaluation of ad locations on any and all websites visited by people who have this extension active. This lowers the direct revenue website owners receive for legitimate clicks.
      - Another facet of damage caused is direct punishment of publishers who generate more than a minimal amount of invalid traffic - ad networks will in response cull anything that can't be strictly verified as legitimate clicks (often in their sole discretion).
      - In extreme cases, publisher accounts may even be shut down entirely.
- Generating this kind of traffic does not achieve its intended goal (providing protest against ad networks or causing advertising to fail for ad networks) since the ones punished are the publishers (those who rely on this revenue) and not the ad networks.
- While it is not considered "click fraud" (because the publisher isn't benefiting from users generating false clicks with AdNauseum -- the opposite, in fact), it is causing problems for the overall health of the Internet economy, especially those who need this kind of revenue to keep their sites and services free to the public.

Because this extension causes direct and indirect economic damage to website owners, it is classified as malware, and as such blocked.
This won't be reconsidered unless and until such time as the "ad click generation" feature has been removed from the extension."

**Comment by dhowe** [comment]
Anyone have additional information on the "responsible ad services" that Pale Moon / Moonchild Productions suggests they use to fund the project?

**Comment by corysimmons** [comment]
@dhowe Is AdNaus officially hosted anywhere else before GitHub turns on you? I suspect this will become a much bigger deal soon and these corporations tend to stick together.

**Comment by dhowe** [comment]
are you referring to the website, the code, or the downloads?

**Comment by corysimmons** [comment]
code

**Comment by dhowe** [comment]
backed up nightly offsite

**Comment by rugk** [comment]
LOL and the palemoon people want to make a better browser than Firefox? Just FYI: no Mozilla is naturally not blocking add-ons, which they don't like.

So suggestion: Just switch back to Firefox and better fight [against Chrome](https://www.cnet.com/special-reports/mozilla-firefox-fights-back-against-google-chrome/). You will get problems with add-ons anyway soon, as pale moon does not seem to support web extensions.

**Comment by hockeymikey** [comment]
@rugk You're being generous towards Mozilla and Firefox.  I would still say PaleMoon is better than Firefox due to all the telemetry and other crap they have baked in. Plus Mozilla is a terrible organization of late and supporting them should be reserved.  I'd recommend Waterfox personally due to the independence from Mozilla, retention of legacy addon support past v57, additional features, and vision of the dev.

**Comment by rugk** [comment]
Yeah, we see here how lovely the Pale Moon organisation is. :laughing: 

So blame Mozilla. That's okay… And some things they do/did is indeed not good, but they could always fix it and make it optional for the user. You don't have to be tracked in Firefox.
And as Waterfox and Palemoon both don't seem to get on the track with the new Quantum engine and (maybe?) electrolysis (as legacy add-ons don't support that). So they will likely hang behind Firefox in terms of performance, security and stability when FF 57 is released and also updates/merging things from upstream could get problematic.
It just does not help to stick to things in the past, in order to improve things, one has to move forward. Unfortunately, legacy add-ons will be dropped by that.

But let's not discuss that further… Anyone is gotta using what they like and blaming whom they (don't) like.

**Comment by hockeymikey** [comment]
@rugk They could fix it but will they?  And is it worth waiting and wishing on daisies?  Most legacy addons support e10s just fine. I'd hardly called a watered down API that is highly restrictive and under-matured a improvement on the past but that's just me.

**Comment by rugk** [comment]
Yes, restrictiveness is a component of security (here).
They fixed many things, they provide many choices.

**Comment by dhowe** [comment]
an interesting discussion, but perhaps not the right forum for it

**Comment by FrostKnight** [comment]
I don't know if this would change your mind, but there are other browsers besides this one, that use UXP as a base...
Also, the blocklist can be disabled, besides the fact that its not the users fault this decision was made.

That all being said, Hyperbola might have use for such an addon, due to ublock origin stalling somewhat.
I am sorry that the lead dev acted that way...

On a side note, things seem to be way more peaceful due to a recent situation on palemoon forums...

Aka, one of the two lead devs has left... things were a thousand times more toxic with him there.

If you don't plan to change your mind, can you tell me, which build you dropped Adauseam from the repo at from the master build?

Also, I am curious how far you got towards making it fully functional before you quit.

Regardless, I do appreciate you trying, as do many other users on that forum.

Also, like at least 20 users quit the forum after he classified your addon as malware.

PS, I am not techically affiliated with Hyperbola, but supposedly, iceweasel-uxp, icedove-uxp, iceape-uxp do not have this issue.  I am merely asking on a whim, because I would like to use this.  Of course, I don't know where to find the legacy build, or if it even works at tnis point, but feel free to contact me if you are willing to continue this.

Not for palemoon itself, but for the users who appreciated the work you did before.

That being said, Hyperbola devs are no fan of spyware, backdoors, malware, privacy invasive ads, etc...

I am sure people there would appreciate it.

As for if firefox is more secure, recent events, seem to indiciate otherwise.

Btw, github currently works for me with a uxp browser, so no worries here.

I do agree though, the below message is insane due to the issue of privacy:

 "Generating fake clicks on ads will flag publisher accounts with "invalid traffic". If this kind of traffic persists, it causes damage for the website owners who run ads:

    One facet of damage caused is direct devaluation of ad locations on any and all websites visited by people who have this extension active. This lowers the direct revenue website owners receive for legitimate clicks.
    - Another facet of damage caused is direct punishment of publishers who generate more than a minimal amount of invalid traffic - ad networks will in response cull anything that can't be strictly verified as legitimate clicks (often in their sole discretion).
    - In extreme cases, publisher accounts may even be shut down entirely.

Generating this kind of traffic does not achieve its intended goal (providing protest against ad networks or causing advertising to fail for ad networks) since the ones punished are the publishers (those who rely on this revenue) and not the ad networks.
While it is not considered "click fraud" (because the publisher isn't benefiting from users generating false clicks with AdNauseum -- the opposite, in fact), it is causing problems for the overall health of the Internet economy,  especially those who need this kind of revenue to keep their sites and services free to the public."

If you feel willing, contact me, I would be willing to test such an idea, beta or stable.

Hope you all are well.

**Comment by nukeop** [comment]
> Generating this kind of traffic does not achieve its intended goal (providing protest against ad networks or causing advertising to fail for ad networks) since the ones punished are the publishers (those who rely on this revenue) and not the ad networks.

It does, by hurting the revenue of those who add spyware to their websites to generate income. It also hurts the revenue of those ad services, since they take a cut every time an ad is displayed.

>  While it is not considered "click fraud" (because the publisher isn't benefiting from users generating false clicks with AdNauseum -- the opposite, in fact), it is causing problems for the overall health of the Internet economy, especially those who need this kind of revenue to keep their sites and services free to the public."

It's not "healthy" to have every single goddamn website on the internet filled to the brim with megabytes of tracking scripts. I don't want such websites to survive. I want them to be heavily disincentivized by removing their ability to generate revenue in this way. That's why I'm using AdNauseam to do my part.

**Comment by FrostKnight** [comment]
I agree with you, otherwise I wouldn't use Hyperbola.
They throw out a lot of bloated garbage, so I COMPLETELY understand you.
Also not fond of redhat creations such as dbus, systemd, pulseaudio, networkmanager, avahi, wayland, etc...

For this very reason...

I would take it a step further, I want google, microsoft and amazon and their idiotic data centers wiped off the map due to their cold indifference to privacy AND making climate change a million times worse!

**Comment by nukeop** [comment]
Wtf is hyperbola and what does redhat have to do with this?

**Comment by FrostKnight** [comment]
Btw, how good is this version of Adnauseum compared to the current one and can it be updated to have the changes needed to work properly without much problem?

adnauseam-3.7.802.firefox-legacy.xpi

I saw this in the repo and I appreciate you not completely deleting all of these.

**Comment by FrostKnight** [comment]
> Wtf is hyperbola and what does redhat have to do with this?

Actually, Hyperbola is a distro that uses a web browser called iceweasel-uxp it is based on the UXP toolkit.

As for your other question, I am mentioning this irritation towards bloat, to convey my dislike of bloated websites.
