### ISSUE TITLE
AdNauseam 3.5 fails to detect/click ads on Windows 7

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1311]
[submitted via email]

The Firefox add on for Win 7 does not work with the latest version of Firefox. Is this a known issue?
It works fine with Opera.

No error messages. Count on icon is always 0 regardless of site visited. 0 ads found or clicked on interface. Same sites with Opera have the counter >0 and the interface auto clicks ads one by one. I have removed ALL add-ons from Firefox and still the issue persists.

**Comment by amrojjeh** [comment]
Having the same issue on Firefox 57.0.2, however, I am on windows 10.

**Comment by dhowe** [comment]
Do either of you have built-in adblocking enabled?

**Comment by dhowe** [comment]
@amrojjeh any other extensions or ad blockers enabled ?

**Comment by dhowe** [comment]
I am unable to recreate this on Windows 7 with Firefox 57 and AdNauseam 3.5

![image](https://user-images.githubusercontent.com/737638/34404726-409f1334-ebea-11e7-9a03-59de084f2927.png)

**Comment by HomoElectromagneticus** [comment]
I am able to recreate this on Windows 7 with Firefox 57.0.3. 
![adnauseam_bug](https://user-images.githubusercontent.com/31375121/34511209-aa082194-f00e-11e7-9781-d7fa405939c5.png)

This occurs with and without Add-Ons.

**Comment by dhowe** [comment]
Can you include a list of the pages you visited so that we can do the same set of tests?

**Comment by HomoElectromagneticus** [comment]
It actually looks like this is an issue with profiles / about:config settings on Firefox. If I use the default profile on Firefox, this issue doesn't manifest itself and I can see ads being clicked (vising walmart.com, for instance). I copied the "bad" profile from my Windows machine onto my GNU / Linux box running Firefox 52.5.2 and was able to replicate the "fails to click ads" behavior with this profile there.

The text issue was resolved by moving to Firefox's default profile as well. 

I've uploaded this "bad" profile here, in case you want to take a look at it. Fair warning - it is quite lengthy.
[user.js.zip](https://github.com/dhowe/AdNauseam/files/1602463/user.js.zip)

**Comment by HomoElectromagneticus** [comment]
So I've done a bit more homework. As far as I can tell, the "fails to click ads" behavior is linked to Firefox's history settings. I haven't tested all combination of history settings, but it looks like the "never remember history" setting and at least a few permutations of "use custom settings for history" are the culprit. I've tested this on both Firefox 57 on Windows and Debian, as well as Firefox 52 on Debian.

**Comment by HomoElectromagneticus** [comment]
I forgot to include the webpages, sorry. I was using:
http://bidace.com/150.html

**Comment by dhowe** [comment]
Thanks @HomoElectromagneticus. This may be because AdNauseam is disabled in Firefox in 'Private' mode, per this [FAQ item]. When you switch off "never remember history", does it start up again?

**Comment by HomoElectromagneticus** [comment]
Tanks @dhowe. That's very interesting - "Never remember history" looks the same as "Always use private browsing mode." Switching off "Never remember history" does make AdNauseam work again in Windows 7. Then if you choose "Use custom settings for history" and tick "Always use private browsing mode," AdNauseam stops working again per that FAQ item. I believe that my previous experiments with this in Windows 7 were not valid, because I accidentally had Privacy Badger running during them. In any case, the above behavior is repeatable on my machine now.

This seems like a messaging issue. Firefox doesn't tell you that "Never remember history" is effectively the same as "Always use private browsing mode." The way to get Firefox to stop collecting browsing history and still have AdNauseam work is to select "Use custom settings for history" and then untick "Remember my browsing and download history" as well as "Remember search and form history."
