### ISSUE TITLE
Ad visible on https://adbtc.top

### ISSUE THREAD

**Issue by KenLiHK** [dhowe/AdNauseam#1438]
### Describe the issue
Visble Ad in https://adbtc.top

### One or more specific URLs where the issue occurs
https://adbtc.top

### Screenshot in which the issue can be seen
Screen in Chrome,
![screen1](https://user-images.githubusercontent.com/24424527/49326135-64c83580-f588-11e8-9b74-b6a3a1473110.png)

Screen in Firefox,
![screen1 firefox](https://user-images.githubusercontent.com/24424527/49326338-bfaf5c00-f58b-11e8-9c43-bf0210f87c81.png)

### Steps for anyone to reproduce the issue
1. Add AdNauseam plugin into Chrome / Firefox
2. Enable "HIDE ADS", "CLICK ADS" and "BLOCK MALWARE" in "About" page.
3. Access the URL https://adbtc.top

### Your settings

- OS/version: Windows 10 Enterprise
- Browser/version: 
  1) Chrome Version 70.0.3538.110 (Official Build) (64-bit)
  2) Firefox 63.0.3 (64-bit)
- AdNauseam version: AdNauseam3.7.802
- Other extensions you have installed: N/A

##### Your filter lists
AdNauseam filters​​​​
EasyList​​​​​
EasyPrivacy​​​​​
uBlock filters​​​​​

uBlock filters – Badware risks​​​​​
uBlock filters – Privacy
uBlock filters – Resource abuse​​​​​
uBlock filters – Unbreak​​​​​
My filters​​​​​

Malware Domain List​​​​​
Malware domains

### Your location/country
Hong Kong

**Comment by cqx931** [comment]
I will use these two rules instead.

##iframe[src*="ad.a-ads.com"]
##iframe[src*="neon.today"]

From this particular website we can see that ad.a-ads and neon.today are two ads providers. So it makes more sense to block any general iframes provided by them rather than any i-frames on the site adbtc.top.
 
One strange thing I have noticed about this website. The adnauseam parser doesn't log anything at all even when I turn on debugging mode. Let's revisit this together next time.

**Comment by dhowe** [comment]
Correct. If a rule is likely to work on multiple sites (i.e., using the same ad-network) then don't make it specific to only one site. Also, as @cqx931 notes, use partial-matching rules (with ^,$,*) whenever possible.
