### ISSUE TITLE
[merge1.17.0] Cookies from ad visits are not blocked in chrome

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#1478]
http://lab-lamp.scm.cityu.edu.hk/adntest/cookie-setting-ad.html

Firefox webExt seems to be okay

**Comment by cqx931** [comment]
This issue seems to be very strange to me. When I check the web request in background.html, there are no "set-cookies" headers, which are the headers processed by `onHeadersReceived`. However, cookies are still set by the php request and if I click the ad, I do see the "set-cookies" headers.
![image](https://user-images.githubusercontent.com/3056154/55693719-9447de00-597e-11e9-886e-98848ddd86ae.png)

**Comment by cqx931** [comment]
@dhowe  Could you please take a look at it?

**Comment by dhowe** [comment]
So the cookie _should_ be blocked, is that correct?

**Comment by cqx931** [comment]
yes！

Sally

**Comment by dhowe** [comment]
I see the following error in the console:

Error in event handler: ReferenceError: browser is not defined
    at µBlock.adnauseam.exports.verifyFirefoxSetting (chrome-extension://bgfakkfcmbdaaeifhgdfeodkafhklfef/js/adn/core.js:1820:36)
    at Object.µBlock.adnauseam.exports.verifyAdBlockersAndDNT (chrome-extension://bgfakkfcmbdaaeifhgdfeodkafhklfef/js/adn/core.js:1816:5)
    at chrome-extension://bgfakkfcmbdaaeifhgdfeodkafhklfef/js/adn/core.js:2129:42
    at Object.<anonymous> (chrome-extension://bgfakkfcmbdaaeifhgdfeodkafhklfef/js/vapi-background.js:998:17)

**Comment by dhowe** [comment]
Ok. So the problem is that for some reason vAPI.Chrome is not being set to true at /AdNauseam/platform/chromium/vapi-client.js::line 46, which is causing all of the Chrome cookie stuff to fail. It seems to me that that whole file isn't being run, though I haven't been able to verify this 100%. @cqx931 any reason why this file would no longer be executed (in chrome)?

**Comment by dhowe** [comment]
So that file does actually get run. But for some reason, vAPI.chrome is not set. You can see the valid properties for the vAPI object in Chrome here:

`["uBO", "setTimeout", "webextFlavor", "download", "getURL", "getViews", "i18n", "closePopup", "localStorage", "cantWebsocket", "lastError", "resetLastError", "supportsUserStylesheets", "insertCSS", "app", "storage", "cacheStorage", "browserSettings", "tabs", "isBehindTheSceneTabId", "unsetTabId", "noTabId", "anyTabId", "setIcon", "messaging", "warSecret", "contextMenu", "commands", "onLoadAllCompleted", "punycodeHostname", "punycodeURL", "adminStorage", "cloud", "getAddonInfo", "net"]`

**Comment by dhowe** [comment]
Ok, so that issue is fixed. vAPI.chrome is now being set correctly. However, only the following headers are shown:
![Screen Shot 2019-04-13 at 12 24 37 PM](https://user-images.githubusercontent.com/737638/56082488-5e27b580-5de7-11e9-825b-e87b2519d232.png)

The 'Set-Cookie' header is not set, though when I use curl to access the same URL, I see:
```

$ curl -i http://rednoise.org/adntest/cookie.php
HTTP/1.1 200 OK
Date: Sat, 13 Apr 2019 16:27:57 GMT
Server: Apache/2.4.18 (Ubuntu)
Set-Cookie: TestCookie=data1
Set-Cookie: TestCookie=data2; expires=Sat, 13-Apr-2019 17:27:57 GMT; Max-Age=3600; path=/
Set-Cookie: TestCookie=data3; expires=Sat, 13-Apr-2019 17:27:57 GMT; Max-Age=3600; path=/; domain=rednoise.org; secure
Content-Length: 53
Content-Type: text/html; charset=UTF-8

```

**Comment by dhowe** [comment]
Thoughts, @cqx931 or @metapea

**Comment by metapea** [comment]
sorry, i have no clue. 
i'm just a tester.

**Comment by cqx931** [comment]
I saw the same for what you mentioned about the headers...I'm not sure about the reasons behind. But what confuses me most is that despite the absence of "set-cookies" from Adnauseam vAPI.chrome, the cookies were successfully set from the ad visit.

A latest observation is that cookies blocking works fine in opera for the latest commit, could this be some tricky thing with the chrome browser?

**Comment by dhowe** [comment]
So the same (test) site works correctly in chromium and opera, but not Google chrome ?

**Comment by cqx931** [comment]
@dhowe yes, that's what I see.

**Comment by cqx931** [comment]
This also seems to be applied to opera right now, and interestingly, if I install something such as "HTTP Header Live" it also can't show cookies related headers from chrome based browsers.

**Comment by dhowe** [comment]
Does [this](https://www.forbes.com/sites/kateoflahertyuk/2020/02/05/new-google-alert-as-experts-warn-chrome-80-cookie-changes-could-break-websites/#43e4a4147714) relate ? I'm wondering if this has to do with the way we are setting our cookies in the tests.

**Comment by dhowe** [comment]
Can see here that our set-cookie calls are being blocked bc of the same-site policy changes
![Screenshot 2020-06-14 at 4 51 12 AM](https://user-images.githubusercontent.com/737638/84578790-f1e57f00-adfa-11ea-82ac-207fbf4eb323.png)

**Comment by cqx931** [comment]
On my side, I only see one warning sign for the last set-cookie, which blocked because of secure connections.

But the first and second cookies do get set successfully and saved in the browser. It's only from the onHeadersReceived that I can't see the first two headers.

**Comment by cqx931** [comment]
The new policy sounds more about why certain cookies can't be set. While the issue we are facing is cookies are set, but we can't get access to these headers within the extension.

**Comment by dhowe** [comment]
I've been adjusting the cookie setting mechanism on the server. If you use http, you should be able to see the first 2 cookies. If you use https, you should see all 3.

I've tested this in the browser itself, but not in ADN ([this](https://www.chromium.org/updates/same-site/test-debug#TOC-Testing-Chrome-extensions) may be relevant if there is a further problem).

**Comment by dhowe** [comment]
We may need to add the 'extraHeaders' field when we register the onHeadersReceived listener (search for 'extraHeaders' on [this page](https://developer.chrome.com/extensions/webRequest))

**Comment by cqx931** [comment]
fixed https://github.com/dhowe/AdNauseam/commit/c3849faa1cc896ed3cf0aea15815e040415f31c5
