### ISSUE TITLE
Add AdNauseam to the Edge store

### ISSUE THREAD

**Issue by Dyras** [dhowe/AdNauseam#1486]
Now that the extension store has finally been opened for Edge, and Chromium extensions can be installed without trouble in Edge, I think it's time AdNauseam makes a much welcomed comeback on a Chrome-based store!

So why not add it to the Edge store? Adblock Plus and TamperMonkey are already on there.

**Comment by dhowe** [comment]
Happy to have it in the Edge store, though we don't have any extra resources to spare -- what is required?

**Comment by cqx931** [comment]
[This page](https://docs.microsoft.com/en-us/microsoft-edge/extensions/guides/porting-chrome-extensions) should be helpful. But installing Microsoft Edge Extension Toolkit needs a Windows OS system...

**Comment by dhowe** [comment]
Ok, so sounds like we need someone with a windows dev machine to handle this...

**Comment by Dyras** [comment]
A Windows 10 development environment for Virtualbox can be downloaded here btw

https://developer.microsoft.com/en-us/windows/downloads/virtual-machines

**Comment by PixelHir** [comment]
Any updates on that?

**Comment by cqx931** [comment]
The link provided by @howdoidoaprogramming works for me. Though there are some issues with the version number in that file.

@PixelHir I will take a look at this, thank you for bringing it up.

**Comment by cqx931** [comment]
https://github.com/dhowe/AdNauseam/commit/4175c1fb4644606264cc3a6bf5439e1ca6252e2e
I have added support for Edge. Now make-artifacts.sh should automatically generate a zip file that is ready to be uploaded to the store!

@PixelHir We decided to officially publish AdNauseam in the Microsoft Store for our next release. As for now, you can install it in developer mode from the following file:
[adnauseam-3.9.104.edge.zip](https://github.com/dhowe/AdNauseam/files/4629739/adnauseam-3.9.104.edge.zip)

Please note that the file is a quick adaptation from the current 3.9.104 release. Since I haven't done any testing on it, there might be Edge specific issues.

**Comment by PixelHir** [comment]
> @PixelHir We decided to officially publish AdNauseam in the Microsoft Store for our next release. As for now, you can install it in developer mode from the following file:
> [adnauseam-3.9.104.edge.zip](https://github.com/dhowe/AdNauseam/files/4629739/adnauseam-3.9.104.edge.zip)

Gonna switch to it from the chrome version, thanks
Hope it won't get taken down from Microsoft Store as well c:

**Comment by PixelHir** [comment]
Any updates on that? Can't find it on edge store so far :v

**Comment by dhowe** [comment]
Planned for the next release of AdNauseam

**Comment by Dyras** [comment]
Seems it's in the store boys
https://microsoftedge.microsoft.com/addons/detail/adnauseam/mlojlfildnehdpnlmpkeiiglhhkofhpb

**Comment by PixelHir** [comment]
Great, I guess the issue can be closed now. Thanks
