### ISSUE TITLE
Twitch.tv ads not blocked when Ublock blocks them.

### ISSUE THREAD

**Issue by dusty-dusty** [dhowe/AdNauseam#1508]
### Describe the issue
amazons force ads still go through when I try and watch a stream. I tired uBlock Orgin and they block it. Also Ublock is on V 1.19.6 while you are still on 1.17.0

we are also missing filters but this is known.

### Steps for anyone to reproduce the issue
Start any parted big streamer there is forced preroll ads.

### Your settings

- OS/version:win 10 current 
- Browser/version: firefox current 
- AdNauseam version:current 
- Other extensions you have installed:

### Your location/country
(If the issue is website specific, knowing your approximate location will help us to reproduce it)

**Comment by cqx931** [comment]
I tried to watch a film using amazon prime and there is a short ad showing up at the beginning that you can choose to skip. I'm not sure whether this is the kind of ads you are mentioning in this issue, if not please include more details on how to reproduce it.

If what I described above is the correct one, uBlock blocks them through web requests like the one below:
`https://s.amazon-adsystem.com/iu3?d=amazon.com&slot=navFooter&a1=010168c17aa321c4af5dafb7d7a1d44464886ce1bddeb70bc533a94c7d7f480940bb&a2=01011d33fbb13fd66580ea5fe108235313253db7fcd41bfe9897a77b5908fd7ea8f7&old_oo=0&ts=1560374425383&s=Ac_SNwxuzzpifPhRLBDdWH2Fi320oV3TfBWeHhA9tKuI&cb=1560374425383`

In my test, I can add this rule to adnauseam.txt to block them
`||amazon-adsystem.com^$subdocument`
 I added `$subdocument` in order to avoid being to generic as we don't want to block the request if it is for an ad image.

**Comment by cqx931** [comment]
close for now, reopen if needed
