### ISSUE TITLE
Ads visible in adnauseam but hidden in uBlock Origin

### ISSUE THREAD

**Issue by Ledarium** [dhowe/AdNauseam#1532]
### Describe the issue

As described in title, those two bars at the sides of site are not hidden in adnauseam. They are blocked with uBO, though
Site: hdrezka.horse

### Screenshot in which the issue can be seen
AdNauseam only, other extensions disabled
![ads](https://user-images.githubusercontent.com/10389237/62313956-a6540c00-b49a-11e9-8cd5-d812a8a548fa.PNG)
![list in adnauseam](https://user-images.githubusercontent.com/10389237/62314007-c388da80-b49a-11e9-8d0c-8d965f206993.PNG)
uBO only, other extensions disabled
![no ads](https://user-images.githubusercontent.com/10389237/62314532-ec5d9f80-b49b-11e9-9299-5bf48016d160.PNG)
![list in ubo](https://user-images.githubusercontent.com/10389237/62314535-eebff980-b49b-11e9-99e5-fdcfeda35222.PNG)

### Steps for anyone to reproduce the issue

Install latest AdNauseam on latest Firefox
Go to hdrezka.horse.

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox Quantum 68.0.1 (64-bit)
- AdNauseam version: 3.8.302
- Other extensions you have installed: disabled all of them

##### Your filter lists
Default filter lists + RUS: AdGuard Russian + RUS: RU AdList, as seen on screenshot

### Your location/country
Russia

**Comment by cqx931** [comment]
Hi @Ledarium this issue should be fixed by https://github.com/dhowe/AdNauseam/commit/0153e78b4ea74f82c82d8ab5a3969afdfd4fa87c
Could you please update the adnauseam filter list and verify the issue? Thank you!

**Comment by Ledarium** [comment]
@cqx931 yep it works, thank you. I don't think it's a proper solution though. I mean, ublock doesn't use this explicit filter yet still blocks those ads somehow, so maybe we should look into this problem further IMO

**Comment by cqx931** [comment]
Thank you for your interest in the project! @Ledarium 
The major difference between uBlock and AdNauseam is that in AdNauseam we want to click and  collect ads whenever it's possible. Therefore, many blocking filters are not used as we do want the ads to be generated first so that we can try to collect them using cosmetic filters. 
If you check the logger, blocking filter on 3rd party braun634.com requests plus other cosmetic filters from from RU AdList are the main reasons why you don't see this ad in uBlock. So I added back this blocking filter to hide the ads, and because adnauseam doesn't support ad collection from background images yet, they are left uncollected by adnauseam.
You can find more about how hiding/blocking works in adnauseam in [this wiki page](https://github.com/dhowe/AdNauseam/wiki/Developer-FAQ#what-is-the-relationship-between-blocking-and-hiding-rules-in-ublock-and-adn) 

If you think there is a better way to solve this issue here, I'm also happy to hear it!

**Comment by Ledarium** [comment]
@cqx931 understood, thanks! Is there any work going on implementing background images clicking?

**Comment by dhowe** [comment]
This would be nice. @cqx931 what would be required?

**Comment by cqx931** [comment]
@dhowe I remember that I have done some work on this very long time ago... shouldn't be very difficult based on what we have now. See: https://github.com/dhowe/AdNauseam/issues/451. I can focus on this and text-ad parsing next time when I work again.

It's more about ad collecting. There is no major difference(at least I didn't notice any) on cosmetic filters between background images and real images.

**Comment by cqx931** [comment]
More about how ad hiding is working in this particular scenario:
```
hdrezka.horse##body:not(#id):style(padding-top: 0 !important) 
hdrezka.horse##body:not(#id):style(background-image: none !important)
```
See [:style()](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#style)
The background image ad in the body tag is hidden by modifying the original css rules, instead of hiding the whole tag. 

Currently AdNauseam does support simple

**Comment by cqx931** [comment]
close for now
