### ISSUE TITLE
Ads visible on webdevelopersjournal.com

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1533]
![image](https://user-images.githubusercontent.com/737638/62407515-a67e0580-b587-11e9-914b-c20125b8a657.png)

**Comment by Ledarium** [comment]
![image](https://user-images.githubusercontent.com/10389237/62409816-9b59c280-b5e5-11e9-92cd-0438a24b6acb.png)
![image](https://user-images.githubusercontent.com/10389237/62409832-f390c480-b5e5-11e9-86fe-6c9e63cf6361.png)

Can confirm, but I suppose it should be reported to uBlock developers, because pure uBO does not block them also

**Comment by dhowe** [comment]
Agreed. Thank you
