### ISSUE TITLE
Location of adnauseam.txt for v3.8.302

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1547]
In my version v3.8.302, when I update this file (https://github.com/dhowe/AdNauseam/blob/master/filters/adnauseam.txt) with a new rule, it doesn't appear to take affect. Only when I update this file (https://github.com/dhowe/uAssets/blob/master/filters/adnauseam.txt) does the rule start to work. 

Is this expected behavior? Why is AdNauseam v3.8.302 not using the new adnauseam..txt location?

**Comment by dhowe** [comment]
Actually, it seems this may be related to an update problem... Can you double-check that update is working correctly (add a rule in github that breaks a test page, then update and make sure the page is broken, then remove the rule, update, and make sure the page works again) ?

**Comment by dhowe** [comment]
There are multiple issues here but possibly caused/compounded by a corrupt FF/AdNauseam profile. Se errors below:

![image](https://user-images.githubusercontent.com/737638/64472441-0bcda380-d191-11e9-82cc-989462760055.png)

**Comment by cqx931** [comment]
I am sure that both the auto update as well as the update button in AdNauseam v3.8.302 updates the list from its current location instead of uAssets.

However, what you asked me to double-check might still not going to work due to Github raw content's Cache control. According to the headers, the default Cache-Control for Github raw content is set to 5 min. 
![image](https://user-images.githubusercontent.com/3056154/64644538-d7502680-d3e0-11e9-9d9c-e2a4c044a367.png)

From my testing, the first update in adnauseam filter is going to work if I make a change in adnauseam.txt in AdNauseam folder. The second update won't work immediately as long as I don't clear cache of the browser. 

I am not sure there is a way to modify the cache control or force it to ignore cache as long as we keep serving it from github raw.

See also: 
https://stackoverflow.com/questions/46551413/github-not-update-raw-after-commit

**Comment by dhowe** [comment]
Hmm. Well I hope that was all that was going on. Closing for now..
