### ISSUE TITLE
Youtube comment dissapear

### ISSUE THREAD

**Issue by RomanJos** [dhowe/AdNauseam#1645]
Hi I don't know why but the youtube comment dissapear when Adnauseum is turned on.
I tried to disable some filter etc but it didn't worked

![image](https://user-images.githubusercontent.com/42180076/77245001-7e790a80-6c1b-11ea-9391-177eb28ecfbd.png)

- OS/version: Windows 10
- Browser/version: Firefox 74
- AdNauseam version: 3.9.104
- Other extensions you have installed:
```
    Clickbait Remover for Youtube
    SponsorBlock
    TrackMeNot
```

![image](https://user-images.githubusercontent.com/42180076/77245173-e2500300-6c1c-11ea-83e1-21d08d078e85.png)
![image](https://user-images.githubusercontent.com/42180076/77245180-f1cf4c00-6c1c-11ea-9b20-8dac185245e0.png)

**Comment by cqx931** [comment]
Hi @RomanJos, thank you for reporting the issue. However, I can not reproduce your issue on my end.
A few things you could try:
1. Go to AdNauseam menu and click on the bottom left icon to bring up this interface.

<img width="202" alt="Screenshot 2020-03-22 at 11 01 51 AM" src="https://user-images.githubusercontent.com/3056154/77252899-4a0e4a00-6c2d-11ea-9944-ec403861957e.png">

2. Click on the eye icon to disable cosmetic filters temporarily
3. If you can see the youtube comments showing up after you disable the cosmetic filters, then the comments must be hidden by some filters in AdNauseam. If not, it should be caused by some other reasons.

To know more about the source of each cosmetic filters, you can bring up the logger by clicking the 
other icon marked with a red rectangle.
Once you have the logger opened, you can refresh the web page and adjust the filter to the following settings to only show cosmetic filters applied to the current web page. 
If you click on each entry, you should be able to know more about the source.
<img width="1127" alt="Screenshot 2020-03-22 at 11 09 00 AM" src="https://user-images.githubusercontent.com/3056154/77252965-cd2fa000-6c2d-11ea-8c0c-e94ffb001ca0.png">

Hope that helps!

**Comment by RomanJos** [comment]
Ohh thank you so much it was all my fault lol I created a filter to remove the coronavirus banner (www.youtube.com###main) and it also deleted the comment lol
Thank you again !
