### ISSUE TITLE
Epic Games "Connect to Github" stops working when AdNauseam is active

### ISSUE THREAD

**Issue by Ryder17z** [dhowe/AdNauseam#1648]
### Screenshot in which the issue can be seen
![img](https://cdn.discordapp.com/attachments/601030071221878784/693180749892812951/unknown.png)

### Steps for anyone to reproduce the issue
See title. The webpage will bring you to github, github sends a request that is never received by Epic, causing the process to fail. 

### Your settings

- OS/version: Win10
- Browser/version: firefox 74
- AdNauseam version: 3.9.104
- Other extensions you have installed: 
Enhancer for youtube
youtube adblock
lastpass

##### Your filter lists
default filters

### Your location/country
sweden

**Comment by cqx931** [comment]
Hi @Ryder17z, thank you for reporting the issue.
The issue is caused by this filter rule from 'Easy Privacy'. 
<img width="440" alt="Screenshot 2020-03-29 at 2 33 37 PM" src="https://user-images.githubusercontent.com/3056154/77857231-4862fa00-71ca-11ea-8795-7aa64092383d.png">

Since this is not an AdNauseam specific issue, I would suggest you reporting this issue to 'Easy Privacy'
```
! Homepage: https://easylist.to/
! Please report any unblocked tracking or problems
! in the forums (https://forums.lanik.us/)
! or via e-mail (easylist.subscription@gmail.com).
```

Or, you can try to add this rule to your own filter list to solve it locally.
```
@@||www.epicgames.com/id/api/*$xhr,1p
```

**Comment by Ryder17z** [comment]
okay. I'll do that. I just paused adblocking for the page as a temporary fix

**Comment by Ryder17z** [comment]
A pr was created on easylist github, so i guess this is resolved. 
https://github.com/easylist/easylist/commit/c3c6e10d6c33e7d30eaa130cf636612bb4a0a9fe
