### ISSUE TITLE
Youtube video ad banner from homepage broke with ad hiding off

### ISSUE THREAD

**Issue by SimonGhoul** [dhowe/AdNauseam#1653]
### Describe the issue

A banner from the youtube's homepage was blocked when it wasn't supposed to be blocked.

### Screenshot in which the issue can be seen

![image](https://user-images.githubusercontent.com/41213690/79030090-5834f380-7b65-11ea-9473-77066f294fda.png)

### Steps for anyone to reproduce the issue
Just go to the youtube.com website. The only thing is that I am always getting the same coachella ad. Below is the output of my logger excluding dom and not blocked ads **(I believe ads blocked by adguard base list)**. 

Here's the filter being used by adguard base list that is blocking the ad:
||youtube.com/get_video_info?*=adunit&$important

### Your settings

- OS/version: Windows 10
- Browser/version: Chrome 81.0.4044.92
- AdNauseam version: v3.9.104

**Comment by SimonGhoul** [comment]
> Since it is caused by a blocking rule from a filter list that is not enabled by default in AdNauseam. I don't think it is an AdNauseam issue if you think the ad should not be blocked here.
> 
> You can add an exception for this blocking rule if you still want to have AdGuard base list enabled and not blocking this ad banner.

I knew I was doing something wrong, I am just new to this extension. So AdNauseam is only responsible for not hiding ads included on filters that are not enabled by default? Is there a way to know which filters are enabled by default? (without doing a reset or something, I just want to keep track of which ones could cause issues)

Also, if I make an exception, does the ad still get clicked?

**Comment by cqx931** [comment]
> So AdNauseam is only responsible for not hiding ads included on filters that are not enabled by default?

 If you noticed anything that shouldn't be hidden, and it is caused by the AdNauseam filter list, we can help to fix that.

---
The following lists are enabled by default
<img width="427" alt="Screenshot 2020-04-20 at 4 51 49 PM" src="https://user-images.githubusercontent.com/3056154/79798593-3c7cda80-8327-11ea-9476-fd07325e7877.png">

---

> Also, if I make an exception, does the ad still get clicked?
It depends. In this scenario, if you add an exception rule for the rule you mentioned above, the banner will no longer be blocked and should be rendered as expected. If at the same time, there is another cosmetic rule that will collect this ad and your ad clicking function is enabled, the ad will still get clicked. 

An ad needs to be first collected so that AdNauseam could click on it. If there is a blocking rule that stops the ad being rendered in the first place, AdNauseam won't be able to collect it. AdNauseam collects ads by filtering through elements hidden by cosmetic rules. If you disable ad hiding, AdNauseam will still go through the same set of cosmetic rules to collect ads.

I hope that helps.

**Comment by SimonGhoul** [comment]
> The following lists are enabled by default

Thanks for the pic, I should had done that when I resetted today (I decided to only enable the filters lists I enabled on ublock origin + all ad lists, instead of having all the filters.)

> It depends. In this scenario, if you add an exception rule for the rule you mentioned above, the banner will no longer be blocked and should be rendered as expected. If at the same time, there is another cosmetic rule that will collect this ad and your ad clicking function is enabled, the ad will still get clicked.

I think I got it, so an exception is still going to make the ad get clicked as long as the exception is not going to the cosmetic filter.
