### ISSUE TITLE
Option to remove ads in vault collected in private mode

### ISSUE THREAD

**Issue by ghost** [dhowe/AdNauseam#1668]
It would be great if there would be an option to hide the ads collected in private mode from the vault. I would prefer not to have any porn ads in my vault, but still use the content blocking and obfuscation provided by AdNauseam.

**Comment by cqx931** [comment]
@randomdev666 Do you still want these ads to be collected in your ad vault? Your description sounds like you would prefer not to collect them in private mode.

**Comment by randomdev666** [comment]
No, I would like to have them blocked and / or clicked, however I would not like to have them show up in my vault.

**Comment by cqx931** [comment]
I see. If they could still be blocked and clicked by AdNauseam, but then deleted from the ad data because you are in private mode(not showing up in the vault), will that be better?

**Comment by randomdev666** [comment]
Yes, that would be a great option

**Comment by cqx931** [comment]
@dhowe Based on what @randomdev666 suggested in this ticket, I think we could add a new option to remove ads collected during private mode (maybe under "EXTRA PRIVACY"? ).
If an ad is collected in private mode, it will be deleted from the ad set after the three clicking attempts.

This could help AdNauseam to better respect users' privacy while still making the basic functions of AdNauseam available in private mode.

**Comment by dhowe** [comment]
This seems sensible/useful -- clarifications:
1. Is this an option in the vault or in settings (I think the latter) ?
2. Do we still show ads and visit results in the menu (I think so)
3. Do we still include the count/cost for these ads in our displays in menu/vault (I think so) ?
4. I assume these ads would also not be included in exports

**Comment by randomdev666** [comment]
Here are my opinions:

1. This could maybe even be both, however I would have suggested settings, too.
2. Sure, showing them within the same browser session is fine I'd say
3. As long as the ads themselves are hidden, that's great. Just saving them as statistics would definitely fulfill this issue. However I think its a lot more work to implement a new "private" type ad.
4. If the ads are removed from the DOM, shouldn't they be gone and thus no duplicates happening? Or is this about duplicates when navigating to new pages?

**Comment by cqx931** [comment]
1. Agree. Having this option in the settings also makes more sense to me. If privacy is the primary concern, this should be reflected in the data itself, not just the visualization.
2. Yes. Though the exact time point when the removal is conducted could be another issue to discuss. If we remove an ad after it's clicked in private mode, the ad will disappear from the menu if the user closes and reopens the menu after the click. (but this should be okay?)
3. An ad with a private flag sounds good to me. We can remove all concrete information about a private ad after three attempts. But since the ads are organized at the moment according to their page key, shall we relocate private ads to a new hash key?
4. If it is from a different page, it won't be considered as a duplicate according to our current standard.  If it is from the same page, are you suggesting that it is possible for another a non-private ad to have the same adhash? That would be an issue if we leave the private ads to their original location in the ad set, but it shouldn't be if they are relocated?

**Comment by dhowe** [comment]
> An ad with a private flag sounds good to me. We can remove all concrete information about a private ad after three attempts. But since the ads are organized at the moment according to their page key, shall we relocate private ads to a new hash key?

We should, I think, try to handle these ads uniformly whether this extra-privacy setting is enabled or not -- so either we hash private-window ads on their pages (internally) OR in a separate bin. If the latter, are we still able to display the page in the vault for users who don't enable this setting ?

**Comment by cqx931** [comment]
Tab or browser close should be a good time to process private ads if the setting is enabled.

What I was suggesting is that we still handle these ads uniformly when they are initially created. Then if necessary we can relocate them in a separate bin if needed on data removal. So if a user has this extra-privacy setting disabled, everything still works as before. 
Also this setting should not influence ads that have already been collected.

**Comment by cqx931** [comment]
I am working on this new feature and did some house keeping on our options page to match with some updates in ublock's settings page. It's getting very long but I hope that's okay.

Under "Extra Privacy", I added the new setting "remove ads collected in private mode". Notice that I have moved "Block fonts" and "Block media" to "Default behavior", they used to be categorized under "Hide ads", but that doesn't really make much sense. A screenshot of the latest ublock settings page is attached for reference.

![Screenshot 2020-06-09 at 9 58 22 AM](https://user-images.githubusercontent.com/3056154/84156644-c435ba00-aa37-11ea-9f36-a60ae69de4d6.png)


![Screenshot 2020-06-09 at 10 05 02 AM](https://user-images.githubusercontent.com/3056154/84157406-b3397880-aa38-11ea-8746-3546bf151a86.png)

**Comment by cqx931** [comment]
firefox handles incognito differently: https://bugzilla.mozilla.org/show_bug.cgi?id=1276025

**Comment by cqx931** [comment]
Please check: https://github.com/dhowe/AdNauseam/tree/privateMode

For this new feature, any ads collected in private mode will be first flagged as private. Then whenever a browser window is closed, adnauseam will clean up all private ads so that any data directly related to the browsing history and the ad content will be removed, while minimal information is kept in the record so that we can still get it counted. The ad will also be relocated to a new page hash, so that the private ad won't be associated with its original pageUrl.

An ad example after clean up:
```
  "57f7f91a90661d53c03a56f50094b647": {
      "id": 1,
      "attempts": 1,
      "visitedTs": 1591752682061,
      "attemptedTs": 0,
      "contentData": {},
      "contentType": "img",
      "title": "",
      "foundTs": 1591752674336,
      "targetUrl": "",
      "pageTitle": "",
      "pageUrl": "",
      "private": true,
      "version": "3.9.104",
      "noVisit": false,
      "requestId": "25800",
      "hash": "57f7f91a90661d53c03a56f50094b647"
    }
```

The vault will still be able to include the private ads in the statistics, but the image/text won't be saved and displayed.

Shall we create a place holder for private ads (only shows the text"private ads" and the total number of ads collected in private mode)

<img width="652" alt="Screenshot 2020-06-09 at 8 52 34 PM" src="https://user-images.githubusercontent.com/3056154/84216297-122dda80-aa97-11ea-8499-de6301994313.png">

**Comment by dhowe** [comment]
This sounds good, though we should verify that we haven't removed any of the fields needed for filtering (how is the ad network determined, for example?). 

Also, I wonder if we really need to move the ads to a separate 'private' bin... What is the thinking here? There should be no way to go from the hash back to the pageUrl. 

Finally, requestId -- what are we using this for? I wonder if it might be linkable, through browser internal data, back to the visited page. Probably not, but if we don't need it, then lets not keep it (also why are we storing the hash inside the hashed ad?).

**Comment by dhowe** [comment]
> For 2 scenarios:
>     If I open the same page from a non-private window, I will be able to see the private ad from 
the menu, which will reveal the pageUrl of the private ads.
>     If the same ad is also collected from the same page in non-private window, the private ad will be a duplicate of this visible ad, which again, reveals the content of the private ads.

Exclude ads marked as private (possibly in combination with timestamp) ?

**Comment by cqx931** [comment]
@dhowe that does work for the vault or menu page, but it is still possible to infer the content/origin of the ads by checking the exported data... I think it's a better practice if we don't just take consideration of the private mode only in visualization, but also for the raw data...

Any more thoughts for what you mentioned about fields needed for filtering?

**Comment by dhowe** [comment]
> Do you mean filtering for ad network? Right now we take targetUrl to determine this, which is currently removed from private ads...Or we can only keep the domain name of the targetUrl so that it can be parsed for ad networks without saving the exact targetUrl. 

I don't think we want to store the domain. But does it make sense to just store the ad-network for private ads? 

> However, I don't think these private ads should be counted for "top sites".

agreed

**Comment by cqx931** [comment]
Merged Private Mode related changes to master branch.
Next:
Add Private Mode feature to release testing.
