### ISSUE TITLE
-

### ISSUE THREAD

**Issue by Skyfire11** [dhowe/AdNauseam#1669]

**Comment by Skyfire11** [comment]
Hey @dhowe 
Is there any progress on this issue? Or should I take the lack of activity as a sign you don't want to deal with any NSFW ads of this type?

**Comment by Skyfire11** [comment]
@cqx931 ?

**Comment by dhowe** [comment]
Please do not address individual developers in order to get attention for a specific ticket. This is an open-source project driven by volunteer work. Someone will pick up the ticket eventually, if/as they have extra bandwidth and no other issues are judged to be higher priority. 

Better still, if you are interested in working on the issue yourself (using the logger and other tools), tell us and we can provide guidance
