### ISSUE TITLE
Preroll video ads showing on youtube

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1671]
Can confirm the issue first raised in an email report

https://www.youtube.com/watch?v=2EppLNonncc

![Screenshot 2020-06-07 at 1 00 59 PM](https://user-images.githubusercontent.com/737638/83960753-fe2f8080-a8be-11ea-924d-77d2aba53fa8.png)

**Comment by cqx931** [comment]
Added a temporary blocking filter fix for this youtube issue: https://github.com/dhowe/AdNauseam/commit/e6682bbe3eca3774d0b1159d312a84a8c7afcce7

A more general solution will be included in the next release after AdNauseam supports a type of filter that disables scriptlet injection added since ublock 1.22.0.

**Comment by hfn1** [comment]
Sounds excellent.

Sent from my iPhone

On Jun 9, 2020, at 07:09, cqx931 <notifications@github.com> wrote:

﻿

Added a temporary blocking filter fix for this youtube issue: e6682bb
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_dhowe_AdNauseam_commit_e6682bbe3eca3774d0b1159d312a84a8c7afcce7&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=EqY2RwQR-VG3CtL0LzAt_2i95_uQxaX-fiVNvnCyuZU&m=h4hWYL9bflbpenzHyKCV6StRA6venaPrHIV-2qwuWSE&s=_T4duXX1kNMsmS05fHy-gLzmuFlJ7_rD-W2xvHObFzY&e=>

A more general solution will be included in the next release after
AdNauseam supports a type of filter that disables scriptlet injection added
since ublock 1.22.0.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_dhowe_AdNauseam_issues_1671-23issuecomment-2D641219020&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=EqY2RwQR-VG3CtL0LzAt_2i95_uQxaX-fiVNvnCyuZU&m=h4hWYL9bflbpenzHyKCV6StRA6venaPrHIV-2qwuWSE&s=wUpXTAbukFil3vahc0coDpGtcy86LZH8CzxYml9-D4M&e=>,
or unsubscribe
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AB5244JGRZL62PDI6NZ5OSTRVYJ43ANCNFSM4NWYY73Q&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=EqY2RwQR-VG3CtL0LzAt_2i95_uQxaX-fiVNvnCyuZU&m=h4hWYL9bflbpenzHyKCV6StRA6venaPrHIV-2qwuWSE&s=d7uboqz01-6S5kHI3iugck5NY4iMtSfp0LTlighoanc&e=>
.

**Comment by ice-fly** [comment]
Adblock also has yet to block them

**Comment by dhowe** [comment]
![image](https://user-images.githubusercontent.com/737638/84466977-52ff3c80-acad-11ea-8177-f8d772725688.png)

**Comment by newusernameforwebsite** [comment]
Experiencing this issue as well. Prerolls eventually broke, but now I'm getting static ads before some videos.

**Comment by cqx931** [comment]
[adnauseam.firefox_master.zip](https://github.com/dhowe/AdNauseam/files/4774528/adnauseam.firefox_master.zip)

**Comment by cqx931** [comment]
[adnauseam.firefox.zip](https://github.com/dhowe/AdNauseam/files/4774532/adnauseam.firefox.zip)

**Comment by cqx931** [comment]
Closing for now.
This should be fixed through the latest release update. It might takes a few days for Firefox to approve the new release though...Please let us know if you still experiencing this issue after updating to AdNauseam 3.9.106!
