### ISSUE TITLE
New permission request in recent update

### ISSUE THREAD

**Issue by Chaz6** [dhowe/AdNauseam#1693]
### Describe the issue
I use AdNauseam in Firefox and it is now asking for new permissions, which I am unsure if I should grant. The permissions requested are:-
* Access IP address and hostname permission
* Monitor extension usage and manage themes

### Screenshot in which the issue can be seen
![image](https://user-images.githubusercontent.com/12680/86258355-a5e45980-bbb2-11ea-8456-8a29d59c23e4.png)

### Steps for anyone to reproduce the issue
Have AdNauseam installed prior to 01/07/2020 and wait for the latest update.

### Your settings

- OS/version: Microsoft Windows 109
- Browser/version: Mozilla Firefox 78
- AdNauseam version: 3.9.104
- Other extensions you have installed: Too many to list
- AdNauseam settings: N/A

### Your filter lists
N/A

### Your location/country
United Kingdom

**Comment by cqx931** [comment]
Hi @Chaz6 

"Access IP address and hostname information" is caused by a recent merge update with ublock origin, please check their FAQ for more explanations:
https://github.com/gorhill/uBlock/wiki/Permissions#access-ip-address-and-hostname-information

As for "Monitor extension usage and manage themes", AdNauseam is using this to check which Add-ons you have installed and enabled in your browser, so that we can show you a warning message if you have also installed other extensions that might have potential conflicts with AdNauseam.

@dhowe 
Shall we also add our own permission wiki? That will be helpful both for the users and for us to maintain the update.

**Comment by Chaz6** [comment]
Thank you for the explanation, it helps me to know that the extension hasn't been hijacked.

**Comment by dhowe** [comment]
>  Shall we also add our own permission wiki? That will be helpful both for the users and for us to maintain the update.

yes, lets

**Comment by cqx931** [comment]
Please check [the new permissions page](https://github.com/dhowe/AdNauseam/wiki/Permissions)

So far we only have one AdNauseam only permission, so I have left the rest to link directly to Ublock's permissions page.
