### ISSUE TITLE
Make ADN work only when user is idle

### ISSUE THREAD

**Issue by mushon** [dhowe/AdNauseam#17]
Think SETI at home for ad clicking. 

This will require a cross platform way of identifying idleness. Depending on its performance this will be set as an opt in or opt out option.

**Comment by CyrusSUEN** [comment]
I think the most resource hungry part is gathering the ads.
If ADN can extract ads only in idle or doing it with the lowest CPU priority, the performance will be greatly improved. 
The downside is also obvious that there will be no real time ads list from the ADN menu (at least not a very accurate one).
At the meantime it could also be an excuse to not to extract every ads on a certain webpage because the user cannot notice it (not real time updating).

To think more about it, for the ADN vault page we can gradually build up the ad collage in the background (as a static HTML web page). Or something like Google maps that it streams data instead of loading and popping all the things at once.

**Comment by dhowe** [comment]
The original ticket here was about only doing ad *visiting* during idle time, yes?
I can't imagine giving up the real-time ad detection feature...

**Comment by mushon** [comment]
Yes ^

**Comment by dhowe** [comment]
Ok, so this needs to a cross platform method for determining browser idle-time (to be added to vAPI)

**Comment by dhowe** [comment]
I think we can realize a simple method for this, simply by checking time since last onPageLoad() in core.js. 

Relates to #252

**Comment by leoneckert** [comment]
potential solution in PR above, checking the time of last onPageLoad and only visiting pages when that time is higher than 20 seconds.
Perhaps there should be an exception for visiting ads when they are clicked on in the vault ( I saw visiting ads while they are inspected already has priority) - or generally disregarding idle state when the user is opening the vault / interacting with ADN.

**Comment by dhowe** [comment]
See #663
