### ISSUE TITLE
AdNauseam blocks the 'Subscribe' button on Peertube

### ISSUE THREAD

**Issue by kozross** [dhowe/AdNauseam#1706]
### Describe the issue

On [at least one Peertube instance](https://diode.zone), AdNauseam blocks the 'Subscribe' button from appearing. If I disable AdNauseam, the button shows up fine.

### Screenshot in which the issue can be seen

![no-subscribe-button](https://user-images.githubusercontent.com/8463904/89130768-c3af3080-d55b-11ea-95ae-6da70c264325.png)

### Steps for anyone to reproduce the issue
(Please be as detailed as possible)

1. Go to [this video](https://diode.zone/videos/watch/playlist/7049a134-c967-450e-b07c-86ab1b9a8ffb?videoId=02d8d5ad-aaad-458a-bfe6-a69ffb1b048e&resume=true) with AdNauseam on.
2. Note the lack of a 'Subscribe' button.
3. Lament.

### Your settings

- OS/version: Arch Linux
- Browser/version: Firefox 79.0
- AdNauseam version: 3.9.109
- Other extensions you have installed: AwesomeRSS, Decentraleyes, Disconnect, SimpleTabGroups, Unpaywall, YouTubeClassic
- AdNauseam settings: [settings.zip](https://github.com/dhowe/AdNauseam/files/5012729/settings.zip)

##### Your filter lists

All listed in the settings file provided.

### Your location/country

New Zealand

**Comment by cqx931** [comment]
Hi @kozross, please notice that this is not an adnauseam issue and the button is hidden due to the following lists you have enabled:
<img width="428" alt="Screenshot 2020-08-02 at 5 43 23 PM" src="https://user-images.githubusercontent.com/3056154/89133143-ab053300-d4e7-11ea-9840-bc87948b4751.png">

If you don't want subscribe buttons to be hidden but still want keep using these lists, you can add the following exception rule to your own filters:
`#@#.subscribe-button`

Hope it helps!

**Comment by kozross** [comment]
@cqx931 Thanks - confirmed that this fixes it! Will close now.
