### ISSUE TITLE
[Brave] Error on Install: "Uncaught (in promise) TypeError ..."

### ISSUE THREAD

**Issue by DiagonalArg** [dhowe/AdNauseam#1707]
Ubuntu 16.04, Brave browser:
Version 0.58.18 Chromium: 71.0.3578.98 (Official Build) (64-bit)

Installed according to the manual install (https://github.com/dhowe/AdNauseam/wiki/Install-AdNauseam-on-Chrome-Without-Google's-Permission).  

AdNauseam 3.9.108

It appears in my Extensions along with the others, and with the standard buttons "Details" and "Remove", but also "Errors" (the latter in red).  Clicking it returns:

> Uncaught (in promise) TypeError: Error at parameter 'extraInfoSpec': Error at index 2: Value must be one of blocking, responseHeaders.

Other extensions:

Cookie AutoDelete
Cookiebro
Decentraleyes
Deluminate
GNOME Shell Integration
Jitsi Meeting
MM3-ProxySwitch
OneTab
*Privacy Badger <-- DISABLED
Privacy Pass
*ScriptSafe
Session Buddy
*uBlock Origin <-- DISABLED
*uBlock Origin Extra
*uBO-Scope
*uMatrix
URL in title
User-Agent Switcher for Google Chrome
WayBack Chrome

I still get the "Your adblocker and adnauseam may conflict."  Do I need to turn off uMatrix?  ScriptSafe?  I really don't want to be running all these scripts...

**Comment by cqx931** [comment]
If I install AdNauseam in developer mode on Mac, Brave browser, I can't reproduce the error message. 

But the warning message "Your adblocker and adnauseam may conflict." should be triggered by "uBlock Origin Extra". It should be safe to use ublock origin extra with AdNauseam since it's working against anti-blocking technologies. So I will make the changes so that our warning notification won't be triggered by "uBlock Origin Extra".

**Comment by cqx931** [comment]
Changed here: https://github.com/dhowe/AdNauseam/commit/a9d97cc26dfec595b7afd898179ead66f4b13b97

**Comment by DiagonalArg** [comment]
When I get a moment, I'll see if I can identify which extension may be causing the error.
