### ISSUE TITLE
Ads on Bomb

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1743]
URL: bombmagazine.org

Using adWizard for redirect: 
![image](https://user-images.githubusercontent.com/737638/105686906-c56a1780-5f32-11eb-97e7-371a0635e5fd.png)

![Screenshot 2021-01-25 at 5 28 20 PM](https://user-images.githubusercontent.com/737638/105687096-04986880-5f33-11eb-8e39-f1e569977a49.png)

**Comment by mneunomne** [comment]
Can't reproduce this ad, tested a few times and only this banner from the website itself shows. Not sure they changed it because it is a particular event happening.

![Screen Shot 2021-02-28 at 12 46 30](https://user-images.githubusercontent.com/4967860/109417224-0090b800-79c3-11eb-8529-247c4c430858.png)
