### ISSUE TITLE
Doesn't click ads in librewolf

### ISSUE THREAD

**Issue by DarkFlame57** [dhowe/AdNauseam#1747]
### Describe the issue
In librewolf browser (firefox fork) ads is blocked but isn't clicked. Only on reddit it sometimes clicks. 

### Your settings

- OS/version: manjaro rolling
- Browser/version: librewolf 85.0.2
- AdNauseam version: 3.9.201
- Other extensions you have installed: default ublock was deleted before installing adnauseam

**Comment by DarkFlame57** [comment]
Well, it works

**Comment by rouben** [comment]
@DarkFlame57 - setting the `browser.contentblocking.category` to `standard` in `about:config` on LibreWolf 109.0-1 seems to fix the issue. Librewolf devs disabled the GUI used to change this in `about:preferences#privacy` on Firefox. In Librewolf this setting is defaulted to `strict` which interferes with Adnauseam's ability to click ads, since the browser blocks the ads before the extension has a chance to click them. I hope this works for you.

Suggestion: the setting above may be a good idea to include on [this FAQ page](https://github.com/dhowe/AdNauseam/wiki/FAQ#why-adnauseam-does-not-work-with-certain-browser-settings). I'd be happy to submit a pull request if there is interest.

**Comment by r3tr0g4m3r** [comment]
Greetings, i have this exact problem with Librewolf, the only way I found to keep this change in "standard" is to create an override file, for example in PowerShell:

```
cd ~
mkdir .librewolf
cd .librewolf
notepad librewolf.overrides.cfg
```
Inside this cfg file override the default setting with:
```
pref("browser.contentblocking.category", "standard");
```

**Comment by Ozidesk** [comment]
Can confirm setting browser.contentblocking.category to standard and privacy.trackingprotection.enabled to false with the override works on Linux Mint 22.04.

**Comment by r3tr0g4m3r** [comment]
Just as a tip, if you are using LibreWolf from Flatpak, the location of the override file is different:
`~/.var/app/io.gitlab.librewolf-community/.librewolf/librewolf.overrides.cfg`
