### ISSUE TITLE
Ads visible on hongkongfp.com

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1748]
https://hongkongfp.com/2021/02/22/12-charged-with-rioting-near-polyu-campus-in-2019-15-others-acquitted-over-national-day-protest-charges/

![image](https://user-images.githubusercontent.com/737638/108655254-a5634f00-7504-11eb-9c4b-440d6276eac7.png)

**Comment by mneunomne** [comment]
A question now, this Ad seems to be added by the page sort of "manually" since they are this website "partners" as the image small banner on the side says so, do we consider all such things as ads or are there exceptions ?

![Screen Shot 2021-02-22 at 18 49 20](https://user-images.githubusercontent.com/4967860/108748382-d2345800-753e-11eb-9991-ea2746416a6f.png)

**Comment by dhowe** [comment]
hmmm, good question... the usual rule is that if an possible ad links to an internal page then it doesn't count, but if it links to an external site, then it does.

But in this case, lets ignore for now, and see if it comes up again on other sites -- if so we can discuss further

**Comment by mneunomne** [comment]
Yeah in this case I checked where was the image hosted, and apparently in the the website own folder, so I guess it can be considered as an internal asset:
[https://hongkongfp.com/wp-content/uploads/2021/02/nordvpn.jpg](https://hongkongfp.com/wp-content/uploads/2021/02/nordvpn.jpg)
