### ISSUE TITLE
[ublock-v1.33.0] Update CSS (with new file for ADN styles?) 

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1770]
Discussion was about creating a separate style file for all ADN CSS rules so that updates to uB CSS doesn't break our display (in settings, menu, vault, etc.). Rules here would have the same name as the uB rules but prefixed (or suffixed) with 'adn-'. We would have to update this file whenever new elements were added to uB, but it would better protect 
against problems when merging. Thoughts @cqx931 ?

**Comment by mneunomne** [comment]
@dhowe thinking more about it... There will be another issue if we create separate files because there are changes **also** in the html files from uBlock - changing the classes, tags and structure of the html (Running through this problem now with the current merge). 

If we consider making our own CSS files, we would need also our own HTML files.

**Comment by mneunomne** [comment]
Styles fixed with https://github.com/dhowe/AdNauseam/pull/1772 and https://github.com/dhowe/AdNauseam/pull/1773

After fixing the issues I think for now it is better to not create separate files, since there are too many interconnected aspects that go beyond simply the CSS files. There are the codemirror libraries, the HTML files tags and possibly also changes in the JS that are dependant on certain class names etc.

We just need to keep track of changes and find ways to adapt as we have been doing so far.
