### ISSUE TITLE
Correctly handle strict-blocking (global and domain-specific)

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1801]

**Comment by cqx931** [comment]
https://github.com/dhowe/AdNauseam/blob/ublock-v1.33.0/src/js/adn/core.js#L1127

This should be left unchanged, because [the place](https://github.com/dhowe/AdNauseam/blob/master/src/js/pagestore.js#L609) when we check this number,  it's before we assign the adnallow to all adnauseam allow requests, so until this point, if result === 4, it means it's strict blocking.

This multiple meaning of result === 4 is truly messy and should better be reconsidered as a universal change on another new result case to keep the consistency, such as: 
adnauseamAllow = 4, strictBlock =5

However, a universal change on result types might bring in other issues so I would suggest to leave it to a future release.

**Comment by cqx931** [comment]
the actions in[ lookupRuleData()](https://github.com/dhowe/AdNauseam/blob/ublock-v1.33.0/src/js/dynamic-net-filtering-orig.js#L403) used to be used for logger, which determines the class attribute of a cell, [see](https://github.com/dhowe/AdNauseam/blob/master/src/js/popup.js#L219).

**Comment by dhowe** [comment]
> https://github.com/dhowe/AdNauseam/blob/ublock-v1.33.0/src/js/adn/core.js#L1127
> 
> This should be left unchanged, because the place when we check this number, it's before we assign the adnallow to all adnauseam allow requests, so until this point, if result === 4, it means it's strict blocking.

do you mean the isStrictBlock function, or the isRedirect function (the link above points to the latter) ?

**Comment by cqx931** [comment]
> > https://github.com/dhowe/AdNauseam/blob/ublock-v1.33.0/src/js/adn/core.js#L1127
> > This should be left unchanged, because the place when we check this number, it's before we assign the adnallow to all adnauseam allow requests, so until this point, if result === 4, it means it's strict blocking.
> 
> do you mean the isStrictBlock function, or the isRedirect function (the link above points to the latter) ?

oh it was pointing to the comments before but now it's okay

**Comment by dhowe** [comment]
Issues remain after latest commit. Domain-specific rules strictBlocks are now being logged but then adn-allowed, rather than being blocked. It may also be the case that we have false-positives for domain strictBlocks (where other items are being logged as strict blocks). The image below demonstrates both cases (notice that each ADN-allow entry in the ub-logger has a corresponding entry in the adn-logger, including the one for the only correct domain strict block: doubleclick):

![image](https://user-images.githubusercontent.com/737638/114280216-dd99ff00-9a6a-11eb-9578-df0e3daa957c.png)

**Comment by cqx931** [comment]
Added back some code in pageStore.js from last build and it seems to fix the local scope for me.

See:
https://github.com/dhowe/AdNauseam/pull/1810

Some justification of implementing this in this particular way for future reference/ resolving potential issues with redirect:
- We need adnauseam to evaluate allow/block at [this location]( https://github.com/dhowe/AdNauseam/pull/1810/commits/f7752628e57aa1c48c089f8dbf2a2397dc14c8f7#diff-d88e38513efe4e855f66a53f0ba00fa16264d07f8d8fe7100cf3131a74fbe0b4R681) so that staticNetFilteringEngine can be evaluated later (whether any static filters are triggered)
- This is also important in the logger cause we don't want to see strictBlocking rule being logged in the logger, but the original blocking rule from the static filters
- But maybe there are still some edge cases that is neglected here(potential false positive)... need more testing cases for strictBlocking?

**Comment by dhowe** [comment]
I feel like it would be useful to create a flowchart that details the lifecycle of a request, and the order in which different types of blocks/allows may happen.

**Comment by cqx931** [comment]
Among all the 4 logredirect locations, I think only the ones that calls pageStores redirect functions are the ones that truely matters. If the function only returns the redirect url if there is one, the redirect url is actually added before that point.
![flowchart](https://user-images.githubusercontent.com/3056154/115213585-f3aa5e00-a101-11eb-9242-92b58245dc75.png)

**Comment by dhowe** [comment]
I"m not sure I understand the numbering: there is no 5 and two 6s, and then we have 4.3 leading to 5.1/5.2...

**Comment by dhowe** [comment]
@mneunomne where do we stand with tests for this issue?

**Comment by dhowe** [comment]
closing pending release testing
