### ISSUE TITLE
Impossible to delete rule from 'my rules' tab ?

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1805]
- to recreate: add a rule, e.g. "* doubleclick.net * strictBlock", 
- save
- commit
- close prefs
- re-open
- attempt to delete rule

**Comment by cqx931** [comment]
seems to me that the the storage and rules are correctly removed in the background but something weird is going on with the code-mirror interface itself.

**Comment by dhowe** [comment]
this seems to be part of a larger problem with code-mirror in 'my rules'
is code-mirror used elsewhere? we need to check the functioning (and css styling) of all code-mirror instances

**Comment by mneunomne** [comment]
Yes there are some other issues when you trying to change a rule from `block` to `strictBlock` for instance, as described here:
> My rules editor -> my rules editor seems to have some problem with strictBlock, after saving and commiting a line with strictBlock the line cant not be change to block allow or noop (when click save, the action changes to undefine and highlighted in codeMirror)...

https://github.com/dhowe/AdNauseam/issues/1738#issuecomment-817148770

I'm not sure the issue is with codemirror, I will try to do some test to at least find out where exactly is the problem coming from.

**Comment by cqx931** [comment]
The issue lies in [setCell()](https://github.com/dhowe/AdNauseam/blob/master/src/js/dynamic-net-filtering.js#L229), which seems to work for adding but not for removing. When [removeFromRuleParts()](https://github.com/dhowe/AdNauseam/blob/master/src/js/dynamic-net-filtering.js#L490) is called, newBitmap should be 0 but now it remains 4 thus, can't be removed.

**Comment by mneunomne** [comment]
@cqx931 Nice, It seems like it is working as expected now. Have also tested changing from `strictBlock` to `block` which was also causing a bug for example, and it is working.
