### ISSUE TITLE
Wrong data in menu

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1828]
4 ads in vault, shows 0/0 clicked/detected
Not sure if this is related to loading the addon as 'temporary'

<img width="396" alt="Screenshot 2021-05-03 at 1 45 04 PM" src="https://user-images.githubusercontent.com/737638/116844511-d7d0ad00-ac15-11eb-9021-5a5fdd8367fc.png">

<img width="617" alt="image" src="https://user-images.githubusercontent.com/737638/116844545-f0d95e00-ac15-11eb-8897-0a8fb682f51e.png">

OSX: 11.3
Firefox: 88.0

**Comment by mneunomne** [comment]
@dhowe I think this is because of the temporary install. Just ran using the `run-firefox.sh` and the information on menu was correct.

Perhaps I will note this on the temporary install instructions? 

![Screen Shot 2021-05-03 at 10 15 32](https://user-images.githubusercontent.com/4967860/116854903-b8775700-abf8-11eb-9ad2-8810310415a5.png)

**Comment by dhowe** [comment]
trying to remember what is the expected behavior if there are no ads for the current page...
I _think_ it should show 0/0 but still display the most recent ads from other pages
so perhaps the behavior in this ticket is actually correct

**Comment by mneunomne** [comment]
@dhowe from what I have observed yes this is expected. Since the text is also "ads detected", the wording for me only makes sense if it is referring to the current website, otherwise it would be "collected". 
Closing for now, we can think if a working can be better, but for me it is fine.
