### ISSUE TITLE
Text-ads on duckduckgo.com

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1848]
Text-ads on duckduckgo are hidden but not collected. Good opportunity to create/edit a custom text-ad filter

examples (2 styles): 
https://duckduckgo.com/?q=cloud+services&t=hc&va=u&ia=web
https://duckduckgo.com/?q=food+delivery&t=hc&va=u&ia=web

As @cqx931 points out, there is already a ddg text-ad filter [here](https://github.com/dhowe/AdNauseam/blob/master/src/js/adn/textads.js#L186)
though apparently it is no longer working

![image](https://user-images.githubusercontent.com/737638/119254114-17703080-bbe7-11eb-9c5d-64fbf8d05e1c.png)

![image](https://user-images.githubusercontent.com/737638/119254213-a3825800-bbe7-11eb-83ce-8f325d9895e2.png)

**Comment by dhowe** [comment]
should probably also test the other existing filters

**Comment by mneunomne** [comment]
I found a solution for the case of duckduckgo, there were two issues going on.

The first is that there isn't enough time for the ads to be rendered when the rule is fired, which seems to be an issue with our parser in general. For me to be able to run the parser when the ads are rendered I had to hack-in a `setTimeout` [here](https://github.com/dhowe/AdNauseam/blob/a61a94dae04590c6822d340cb036cc626520a11a/src/js/adn/textads.js#L424):
```js
const process = function (elem) {
        // domain specific
        if (vAPI.prefs.textAdsDisabled) {
          console.log("adn: texts-ads disabled");
          return;
        }
        setTimeout(() => { // TIMEOUT HACK
          const ads = checkFilters(elem);
          console.log("[PARSED] checkFilters ads", ads);
  
          if (ads) {
  
            for (let i = 0; i < ads.length; i++) {
              if (typeof ads[i] !== 'undefined') {
                if (vAPI.prefs.logEvents) console.log("[PARSED] TEXT-AD", ads[i]);
                  vAPI.adParser.notifyAddon(ads[i]);
              }
            }
          }
        }, 2000)
      };
```

-------------

The other issue is that this condition was never true, since the trigger `elem` was a parent that contains multiple `.result___body`, rather then the element itself:
https://github.com/dhowe/AdNauseam/blob/a61a94dae04590c6822d340cb036cc626520a11a/src/js/adn/textads.js#L322

For that I propose this solution, since sometimes the trigger is the parent element and not the ad element itself. I won't think this will cause any problem since further on there are more checks before the ad is registered:
```js
        if (elem.contains(qa[length]) || elem === qa[length]) { // sometimes the trigger is the parent to the query, sometimes it is the element query itself
```

------------

Both of these changes are commited here https://github.com/mneunomne/AdNauseam/tree/%231848. If you want to test it you need to un-comment the setTimeout in the process function in the `textads.js` file. We should be able to merge when we have found a reasonable solution for this more global issue with ad collection https://github.com/dhowe/AdNauseam/issues/1838 

------------

For now the text collection is only working on ask.com. I will see what I can do about the others.

**Comment by mneunomne** [comment]
Closing. Fixed with https://github.com/dhowe/AdNauseam/issues/1848
