### ISSUE TITLE
Ads on wordpress site

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1853]
https://immanentterrain.wordpress.com/2011/04/26/what-is-a-minor-literature-3/

<img width="900" alt="image" src="https://user-images.githubusercontent.com/737638/120151018-5e30dc80-c21e-11eb-8de0-55f3484316b6.png">

**Comment by dhowe** [comment]
adds appears to be hidden (and collected) but not properly collapsed:

<img width="1007" alt="image" src="https://user-images.githubusercontent.com/737638/120307603-c3133200-c305-11eb-80c2-b4e7608200cf.png">

**Comment by mneunomne** [comment]
I'm wondering if this issue is related to this:
https://github.com/dhowe/AdNauseam/blob/e721e10a91c711ea54a980e652a7f8d2e9182c9d/src/js/contentscript.js#L1533-L1534

Because this ad is actually a case of an empty src iframe, and the line of code above is not doing anything, unused variable, something is missing.

**Comment by mneunomne** [comment]
This is missing:
https://github.com/dhowe/AdNauseam/commit/249532b604958db593af6ec9e70b0cf1fda26f99#diff-7c975d431b3d370b6b59f5860b06ddfdfc44eeafc32ef49dd705b13be13446edR1375

**Comment by mneunomne** [comment]
Seems to be working for me. This can be closed.

![Screen Shot 2021-06-02 at 10 36 46](https://user-images.githubusercontent.com/4967860/120452319-6a3dab00-c392-11eb-9354-f466b844614d.png)
