### ISSUE TITLE
Video ads on mirror.co.uk

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#2020]
v3.12.0

https://www.mirror.co.uk/sport/tennis/novak-djokovic-live-news-arrest-25900155

<img width="751" alt="Screenshot 2022-01-10 at 9 17 40 PM" src="https://user-images.githubusercontent.com/737638/148772423-c70123ac-7e79-443b-a4e2-d939aeab7ff9.png">

**Comment by mneunomne** [comment]
For some reason v3.12.0 is allowing more googlesyndication requests to go through, now sure why

v3.11.4
![Screen Shot 2022-01-10 at 15 00 09](https://user-images.githubusercontent.com/4967860/148778280-716079d4-1af2-4073-815c-f308378087bb.png)

v3.12.0
![Screen Shot 2022-01-10 at 14 59 53](https://user-images.githubusercontent.com/4967860/148778272-dad08d5c-afec-43f3-b88a-91b92818bc09.png)

**Comment by mneunomne** [comment]
Apparently is an issue with video ads in general (but not youtube)
https://ge.globo.com/#v/10197197

**Comment by mneunomne** [comment]
This apparently started in the merge from 1.37.0 to 1.38.0

**Comment by mneunomne** [comment]
In relation to what i can test (the $important block not working from "My Filters) the following line is not behaving as in 1.37.0:

https://github.com/dhowe/AdNauseam/blob/92b42a7c770958236051c12c3bab92c88e09212f/src/js/pagestore.js#L849

It's tricky because the part of the `staticNetFilteringEngine` change places and some functions don't exist anymore. At the time of the merge I found this alternative which is using `matchRequest` instead of the original `matchString` but it seems to be causing some kind of issue.

### How I tested:

I added the following request to `My Filters`:
```
imasdk.googleapis.com^$important
```

Then access this page: https://ge.globo.com/

(It will work in any other adn-allowed request)

Then check if the request related to `imasdk.googleapis.com` will be blocked or not. 

I catched this exact request by adding this on pagestore `filterRequest` function:
```
      filterRequest(fctxt) {
        fctxt.filter = undefined;
        fctxt.redirectURL = undefined;
        if(fctxt.includes("imasdk.googleapis.com")) {
            console.log("here")
        }
```

Then what I noticied is that in version 1.37.0 the `result` variable after the specific line mention at first turns into `1`. 

On version 1.38.0 it remains `0`, meaning that it is not finding the filter in `My Filter` related to this request...

**Comment by mneunomne** [comment]
@dhowe Created a test file. This is perfect because this script makes create a visible ad, so its easier to see if it is working or not:
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>adn-allowed script</title>
</head>
<body>
  <p>adn-allowed file "https://uploaded.to/js/layer.js" being loaded</p>
  <script src="https://uploaded.to/js/layer.js"></script>
</body>
</html>
```

**Comment by mneunomne** [comment]
@dhowe  the PR apparently fixes it. both the `$important` issue as well as the ads appearing

**Comment by mneunomne** [comment]
Fixed, closing
