### ISSUE TITLE
The Add-On doesn't show how many Blocked/Clicked Ads

### ISSUE THREAD

**Issue by dhuschde** [dhowe/AdNauseam#2174]
### Describe the issue

The Add-On blocks everything, but doesn't show it.
On the uBlock view, I can still see everything as normal.

### Screenshot in which the issue can be seen
![grafik](https://user-images.githubusercontent.com/85834680/190515038-5065c2f1-d132-4f91-b808-d2e27b39cfed.png)

### Steps for anyone to reproduce the issue
* Install the Add-On

### Your settings

- OS/version: Windows 11 / Linux Mint 20.3 Cinnamon
- Browser/version: Firefox 104.2
- AdNauseam version: 3.14.5
- Other extensions you have installed: I also tried this on a clean Firefox install, so none :)
- AdNauseam settings: Everything on Default, except the Recommended changes (Enabling AdBlocking, Clicking and MalwareBlocking)

### Your location/country
Germany

**Comment by mneunomne** [comment]
It seems that the german translation is a bit off, it is supposed to say "No Ads collected on this page", rather than "there are no ads on this page".

- [ ] Adjust german translation

Regarding the ammount of ads that we can collect, it really varies on different websites, we cant collect a huge ammount of ads for many different reasons, but it tends to collect ads rather consistently if you use on your usual browser.

And if you want to see the uBlock menu with the number of blocked ads, you should click here:

![Screenshot 2022-09-16 at 13 19 52](https://user-images.githubusercontent.com/4967860/190627916-595bf245-db5c-4bad-a564-858f83b37e6f.png)

**Comment by mneunomne** [comment]
Adjusted the german translation to:

```
Keine Werbung auf dieser Seite gesammelt (aktuelle anzeigen)
```

Closing
