### ISSUE TITLE
FAQ: "Aren't all clicks on ads dangerous?"

### ISSUE THREAD

**Issue by corysimmons** [dhowe/AdNauseam#231]
I see a lot of people with this concern about this software. Probably spurred by [the NYT ransomware fiasco](https://www.theguardian.com/technology/2016/mar/16/major-sites-new-york-times-bbc-ransomware-malvertising).

**Comment by dhowe** [comment]
Good suggestion

**Comment by mushon** [comment]
yeap, definitely worth addressing. Is there a way for us to test this potential vulnerability?

**Comment by corysimmons** [comment]
It would seem like any event (e.g. a timeout) would be able to trigger bad stuff.

**Comment by dhowe** [comment]
I wonder if this FAQ entry addresses (at least in part) the concerns here: https://github.com/dhowe/AdNauseam/wiki/FAQ#isnt-it-safer-just-to-use-an-adblocker-why-engage-with-ad-networks-at-all

**Comment by corysimmons** [comment]
@dhowe Yup, looks good.

Although, I'd really like to know a bit more about the dangers of clicking on ads in more detail to help me decide if I want to use this or not. I'm still struggling to understand what the difference in a click event and a timeout event is in that context. Would the "threat" would be the same if someone simply didn't have an ad-blocking service?

I'm kinda waiting on those benchmarks as well, but I love projects like these and would love to see a Brave-like browser that implemented a ton of artware (should this be activismware or actware for short? this is new lingo to me).

**Comment by dhowe** [comment]
Can you clarify what you mean by a timeout event? Do you mean when an AdNauseam visit times out before receiving a response? In any case, like with speed, the high-level picture is that AdNauseam will be safer than using the web with no adblocker, but not as safe as using a strong adblocker like uBlock (depending on the lists you select). AdNauseam does blocks malware and non-visual trackers which is important, however it cannot block ads outright (otherwise it could not collect, display, and click on them). While we're still investigating the ransomware case, the conclusion thus far is that ajax requests (which we use now for our visits) are unable to trigger software downloads of the kind used, at least without some user interaction (though, as I say, I am still investigating this, and welcome any finding to the contrary)...

**Comment by corysimmons** [comment]
A `setTimeout` event is the same as a `click` event correct? http://codepen.io/corysimmons/pen/vKGdQj https://developer.mozilla.org/en-US/docs/Web/Events

According to your last sentence, it seems like not all events are created equal.

**Comment by dhowe** [comment]
I'm assuming you mean a `timeout` [event](https://www.w3.org/TR/XMLHttpRequest/#the-timeout-attribute), generated from an ajax call not returning in time, rather than the `setTimeout` function, but I'm still not sure I get the question. Are you suggesting that malicious code in the result from an ajax request could simulate a download file click? That might be true if the returned javascript was allowed to execute,  but it is not.  The W3C Specification for XMLHttpRequest states:

“Scripts in the resulting document tree will not be executed, resources referenced will not be loaded and no associated XSLT will be applied.”

http://www.w3.org/TR/XMLHttpRequest/#document-response-entity-body

**Comment by corysimmons** [comment]
👍
