### ISSUE TITLE
AdNauseam is removed from extensions upon browser restart

### ISSUE THREAD

**Issue by mikii123** [dhowe/AdNauseam#2339]
### Steps for anyone to reproduce the issue
1. Chrome Version 114.0.5735.134 (Official Build) (64-bit)
2. Load unpacked AdNauseam.
3. Close Chrome.
4. Reopen Chrome.
5. Open extension list and observe. AdNauseam is not on the extension list after restart, doesn't load, doesn't work. Adding it again and restarting the browser has the exact same effect.

### Your settings

- OS/version: Win10Pro 22H2
- Browser/version: Chrome Version 114.0.5735.134 (Official Build) (64-bit)
- AdNauseam version: 3.17.0
- Other extensions you have installed: none
- AdNauseam settings: default

**Comment by dhowe** [comment]
Thanks for the report -- can you verify that the (unpacked) AdNauseam folder is still in the same local location as when it was installed ?

**Comment by Quezako** [comment]
I had the same problem with 2 profiles under Chrome 115.0.5790.171 64 bits, under Windows 11.
I renamed the folder and now it keeps loading after restart.

**Comment by mikii123** [comment]
@dhowe yes, AdNauseam folder is still there.

**Comment by dhowe** [comment]
@mneunomne ?

**Comment by mneunomne** [comment]
Sorry for the delay. Usually yes this happens when the folder is changed location OR when there is some conflict between two version of the extension and you need to change the location of the folder or rename it and install it once again.

This happened to me when we had the manifest id change and it created a conflict on chrome, where if i installed the extension again from the same folder location and the version with the different id, it would generate this issue. This happens because chrome uses the folder location of the unpacked extension as some sort of key for a cached folder.

Not sure why this happened on your case, but the solution is to change the location of the installation usually.

**Comment by dhowe** [comment]
closing for now
