### ISSUE TITLE
Doesn't function in Firefox 117, or requires a disable/enable toggle?

### ISSUE THREAD

**Issue by kode54** [dhowe/AdNauseam#2375]
### Describe the issue

The add-on doesn't appear to be able to function in Firefox 117. The status menu reports that the add-on is "paused" on all sites, and reports a click count of "clicked {{number}} /  {{count}} Ads detected" for every page.

Upon further testing, disabling AdNauseam and re-enabling uBlock Origin, then disabling uBlock Origin and re-enabling AdNauseam, it started working again. I will report if it continues to work after restarting the browser.

I first noticed this happening on IMDB. I thought the fact that ad banners were constantly rotating meant that it was doing its thing even though it wasn't hiding them.

### Screenshot in which the issue can be seen
I need to collect a broken screen shot again, if it does it again.

### Steps for anyone to reproduce the issue
1. Update Firefox to 117 (current stable)
2. Note that AdNauseam is not functioning

### Your settings

- OS/version: Arch Linux
- Browser/version: Firefox 117.0
- AdNauseam version: 3.17.0
- Other extensions you have installed: 1Password, Ambient Light for YouTube, Bing Chat for All Browsers, Don't F*** With Paste, Enhancer for YouTube, GNOME Shell Integration, Plasma Integration, Streetpass for Mastodon, Stylus, The Stream Detector, User Agent Switcher and Manager
- AdNauseam settings: (The defaults)

##### Your filter lists
Default filter lists

### Your location/country
US, California

**Comment by kode54** [comment]
Restarted Firefox. Seems to still be working. Must have been a missed extension update or something.

**Comment by dhowe** [comment]
Closing for now

**Comment by gohellp** [comment]
It happened to me. Initially, I noticed by the way the "strict mode" started to turn off constantly, and instead of the number of clicked ads, formatting values began to be shown at the top of the pop-up: `{{number}} / {{count}}`.

My Specifications:
- OS: Windows 11 24H2, build 26100.6584
- Browser: Firefox 142.0.1
- AdNauseam version: 3.25.8
- Other extensions you have installed:
    - Translator (translator-poqdev)
    - ActivityWatch Web Watcher
    - Simple Tab Groups
    - SponsorBlock
    - Twitch Channel Points Autoclicker
    - Wayback Machine
    - YouTube NonStop
- AdNauseam settings: default

My location/country:
Russia, Central Federal District

Additional info:
This started happening after I reinstalled Windows. The reinstallation was from Windows 11 24H2 to Windows 11 22H2 and upgraded to 24H2.
