### ISSUE TITLE
Google account with ADN flagged as underage

### ISSUE THREAD

**Issue by mneunomne** [dhowe/AdNauseam#2439]
Based on a user report at https://addons.mozilla.org/en-US/firefox/addon/adnauseam/reviews/2009246/ whereby an account was flagged by Google as 'under-age'. This is, at least thus far, a one-off case with no discernible link to the use of AdNauseam. Nonetheless an interesting discussion continues below.

**Comment by dhowe** [comment]
Do we have steps to recreate this issue ?

**Comment by TranscendentThots** [comment]
- To clarify, it didn't claim I was under 18. It claimed I "may or may not be under 18" and gave me buttons to click on to "attempt to resolve" the problem.
- Instead, I deleted my Google account afterwards because I wasn't using it for anything important to begin with, and I interpreted this form of enshittification as a deliberate strategy by the platform to try and fingerprint my account for some unknown nefarious purpose, so unfortunately I can not easily reproduce or even take a screenshot of the [+] icons.
- It's possible that YouTube makes assumptions about visitors when actual metrics are not available.
- If youtube serves _completely random_ ads to "unknown" visitors, clicking on an ad for a childrens' product may be a trigger that makes the algorithm assume you're a child.
- Likewise, clicking on an ad for something only adults would need, like investment services, might make the algorithm assume you're an adult.
- I remember that I had dragged the "how often does it pretend to click on ads" slider almost but not quite all the way to the left. So "how many times the user clicks" might be a leading indicator of what the algorithm does in order to identify users.
- In 'the real world," the algorithm's choice of ads, the user's behavior, and the profile youtube is always building on each user, and the video recommendations feed are processes that operate in lockstep, reinforcing and modifying each other.
- Since clicking on completely random products is not something a real user would do, this _may_ be a deliberate strategy to distinguish "typical" users, who fit comfortably into different buckets for advertising purposes, from "fake" users, who click all products and services equally.
- There may be other "fake user" buckets than "may or may not be under 18."
- You could try building different versions of AdNauseum and testing them using different settings. Make a new Firefox Profile, install AdNauseum, set the Fake Click Rate, Watch a couple videos, and then disable AdNauseum and see if the platform gives you any weird warning or error messages, or seems to have otherwise flagged the account.
- It might be fundamentally impossible to perfectly mimic the behavior of normal users, especially if youtube does something unusual server-side that would cause a human to twig on different properties of the content than a machine is capable of understanding. (I.E. serving business ads from a toy company's advertising account, just to see if the user's behavior conforms to the source URL or the content.)
- As a side note, I've noticed that whenever I make a new firefox account to try and keep my activities compartmentalized, random elements on a platform such as the placement of ads or buttons, the size of borders, headers, breaks and whitespace, and sometimes even branding elements, vary from account to account. It's unclear to me what the purpose of these changes are, but I doubt it's random. Maybe it's to fingerprint users over VPN or something? It's also unclear who, specifically, this New Account RNG is supposed to help, ISPs, platform holders, or law enforcement agencies.
- If we assume that Full Enshittification is the desired endgame of all publicly-traded online platforms, and that the prime interest rate going up means that the so-called "growth mindset" era is finally coming to an end, this _may_ be a component of Big Tech's endgame, where they implement techno-feudalism and divide the world by user (not by account or device) into technological haves and technological have-nots.
- And finally, this is a bit of a rant, but bear with me: Tech articles and cryptic statements by politicians have, for a while, now, been openly hinting that the free and open internet is going to come to an end "eventually." If this is one of the things those comments were in reference to, it may mean that everything from legislation to law enforcement to TOS changes is all being coordinated in order to do whatever it is YouTube is trying to do here. (Force people to watch ads? Force everyone to use a single account tied to their real contact information? Kick political undesirables off the internet? Silence certain voices so they can push through more draconian legislation?) We don't know and we have no way of knowing. What we do know is that they're afraid to talk about it publicly, lest the public weigh in. It's impossible to prepare for a coming sea change or any specific form of retaliation from authorities, but do what you can to protect yourselves and your families, online and off. We don't know what Google is up to right now. All we know for sure is that it's the opposite of "Don't Be Evil."

**Comment by r7l** [comment]
Why use a Google account in the first place? Even more so being logged in with it. Reading your comment, you're not very supportive of their company, business model or general way of thinking. Using an extension like this, you might be better off avoiding accounts by companies using the information you provide. A life without (or minimal) a Google account is easily possible.

**Comment by mneunomne** [comment]
@TranscendentThots your insights are valuable in the broader context of google account usage and privacy, but it seems to me that this issue you have experienced might be really hard to reproduce, and if so, would be a lot of time to have different google account freshly created with and without adnauseam to compare the behaviour, auto-click on some particular ads to see if this flagging was caused by adnauseam. 

My assumption would actually be that since its a freshly created account google perhaps flags it as someomne underage trying to create different accounts? At least this seems to me a more plausible assumption than this being AdNauseam based.

AdNauseam is compatible with other privacy extensions/browsers and feel to free to use them along side. 

I would suggest that we move this topic to the [discussion](https://github.com/dhowe/AdNauseam/discussions), unless we find some clear ways to reproduce this behaviour.

**Comment by TranscendentThots** [comment]
Actually, let me try to reproduce it, real quick.

I'll type what I do and let you know if it worked.

**Comment by dhowe** [comment]
Note that creating a new Firefox profile does _not_ necessarily result in a new google profile. In fact, it is more likely that other tracking means, e.g., via IP, or via browser fingerprint, etc,. will still identify you as the same user, but one who has been creating many new browser profiles

**Comment by TranscendentThots** [comment]
Okay. But that doesn't make sense. If I'm the same user who got flagged as "possibly under 18" yesterday, then that means that Google knowingly showed someone who was possibly under 18 porn today. If I'm the same person who deleted their account the other day, then why are the search results actually worse now than they were then?

If Google already knows who I am, then they are using that information to do everything under the sun _except_ show me relevant ads and videos. That's not even enshittification. I don't know what that is. Who pays them? Who benefits from this? I don't get it.

**Comment by mneunomne** [comment]
@TranscendentThots one quick note regarding your testing. We can't at the moment auto-click ads on youtube, we are just blocking. Only certain types of ads we can collect and auto-visit. So i'm not sure 

I won't close this issue for now as you have requested, but it seems abstract what is the behaviour you are trying to reproduce, and I can't invest time in it at the moment. To understand the impact of auto-clicking ads in the algorithm behaviour of each google account is a matter that would take full data research to reach any sort of meaningful conclusion, and it is not the scope of what we can manage at the moment with AdNauseam I believe (we are currently 2 people).

But feel free to share here more discoveries that you make, since it is interesting to us and other users.

**Comment by dhowe** [comment]
This is a very interesting area of research (to me at least), touching on privacy, algorithmic fairness and bias, to name just a few areas -- and its clear more work need to be done. 

Here is one related paper but not-so-recent paper: https://www.technologyreview.com/2015/07/06/110198/probing-the-dark-side-of-googles-ad-targeting-system/

and our own, vaguely-related experiments in the same publication: https://www.technologyreview.com/2021/01/06/1015784/adsense-google-surveillance-adnauseam-obfuscation/

Would be great if others could post additional links to relevant articles/papers here.

**Comment by TranscendentThots** [comment]
Basically, my concern is that Google wouldn't be flagging accounts in such a weird way if it weren't planning on axeing a bunch of end-users later as a step in enshittification. There's obviously nothing you can do about Google's internal practices, but if running ad blockers is what's actually been degrading the user experience of Search all this time, it would be nice to know about it.

This doesn't strike me as a corner case. This strikes me as the general case. Frankly, I wasn't using ADN long enough to become a corner case. (Although I'll admit, I did tweak a slider, so not a truly default case.)

**Comment by TranscendentThots** [comment]
Also, side-note: Why is the default behavior "click on 100% of ads?" Why not .01% or a random figure between 0.1% and 0.3% or whatever the average is?

Metaphorically speaking, if this is Privacy Gurellia Warfare, you're showing up in the demillitarized zone blaring rock music from the back of a neon-covered monster truck.

**Comment by mneunomne** [comment]
@TranscendentThots Perhaps if we want to continue this discussion, we should do it in the discussion page. This is not an issue we can possibly reproduce, so I will be closing here.
