### ISSUE TITLE
Disable/Re-enable UI is confusing

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#2462]
v3.18.0

Disable UI is confusing: not clear after clicking `disable` whether one needs to click again on `domain` to make the disable active. 

I think a better solution might be to always pop-up the page or domain option without any preselection. Then the user _must_ select one or the other, which causes the pop-up to close

There also seems to be no way (at least sometimes) to un-disable a site/domain (see image below, where clicking on `disable` for the already disabled site does nothing. How is this supposed to work ?

See also #2453

![image](https://github.com/dhowe/AdNauseam/assets/737638/3c3d95b8-131f-49f5-83ce-e06f88fe1490)

**Comment by mneunomne** [comment]
Yes, I implemented this way replicating how ublock works, where to there is no direct way of changing the scope of a disable while already disabled - need to re-enable it and then re-disable choosing the spec. I agree its confusing, will implement it.

**Comment by mneunomne** [comment]
The issue of changing this implementation, is that ublock doesn't have a property to distinguish if the current "trusted pages" hit is coming from a page-specific scope, or a domain specific scope. And since we don't have this information from the popupData, we cant set which of the scopes is the current active one.

I can implement this distinction, but it will require some changes in uBO's code in the netFilteringSwitch, to return some extra properties so it can be displayed in the UI.

**Comment by dhowe** [comment]
Let's first answer the question of whether we can re-enable a site/domain after disabling (and whether this is intuitive)? Please test/document @mneunomne 

I'm not sure switching scope is even necessary

**Comment by mneunomne** [comment]
This has now been fixed https://github.com/dhowe/AdNauseam/issues/2516 Closing

**Comment by dhowe** [comment]
As discussed, lets change the text on the 3 buttons at menu bottom:

active:     [ active*, strict, disable ]
disabled: [ activate, strict, disabled* ]

* indicates blue button
