### ISSUE TITLE
Adn may conflict with DeArrow extension

### ISSUE THREAD

**Issue by CookieSalesman** [dhowe/AdNauseam#2540]
### Describe the issue

DeArrow changes video thumbnails and titles to be less clickbaited (user-sourced).

With ad nauseum up, it appears to be broken. I can't click the edit button (pencil) to submit my own title.

### Screenshot in which the issue can be seen
![image](https://github.com/dhowe/AdNauseam/assets/9441933/9a678291-a4bb-430c-b085-f187a4f38cea)

### Your settings

- OS/version: Windows latest
- Browser/version: FF
- AdNauseam version:  latest
- Other extensions you have installed: a crapton, including privacy badger and DeArrow. But i've toggled adnauseum on and off on YT.
- AdNauseam settings: probably no change

### Your location/country
(If the issue is website specific, knowing your approximate location will help us to reproduce it)
WEst coast

**Comment by mneunomne** [comment]
Hey @CookieSalesman I tested DeArrow with AdNauseam installed, and it is working fine for me. Are you still experiencing this issue? Because on my test it was on youtube new watch-video interface, and taken from your screenshot, it was still the old interface for you. Or perhaps there are other extensions that combined with AdNauseam are causing the issue.

**Comment by dhowe** [comment]
Closing for now, pending further comments
