### ISSUE TITLE
Test Release v2.3.0 rc2

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#282]
[Download](https://github.com/dhowe/AdNauseam/releases/tag/v2.3.0.2) and test on Firefox, Chrome, Opera:

- [x] check the AdNauseam version number
- [x] test a set of pages for each, and make sure that ads are being captured and visited
- [x] test the options (click-ads, block-malware, hide-ads)
- [x] test the header-options (cookies, referer, user-agent )
- [ ] test that no ads are collected in incognito/private-browsing windows
- [x] check general function of menu and vault
- [x] test import/export/clear functions

**Comment by CyrusSUEN** [comment]
> test that incoming cookies are being blocked for adn-visits

removed from the checklist because it's not fixed and in a new ticket: https://github.com/dhowe/AdNauseam/issues/283

> test that no ads are collected in incognito/private-browsing windows

incognito mode works fine usually but not when it shares the same URL with a tab from normal mode: https://github.com/dhowe/AdNauseam/issues/284

> check general function of menu and vault

The problem has been getting worse that actually no matter the number of ads in Vault, it always zooms to 200% after exiting lightbox mode: https://github.com/dhowe/AdNauseam/issues/277

**Comment by dhowe** [comment]
please test 2 other URLs for incoming cookies

**Comment by CyrusSUEN** [comment]
> test 2 other URLs for incoming cookies (www.cicaf.com.json and travelmama.com.hk.json)

No cookies collected from these ads.
