### ISSUE TITLE
Single 'Install AdNauseam' button on home page that installs (inline) for correct browser

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#291]
Or at least goes directly to the relevant page in chrome/opera/mozilla stores

**Comment by CyrusSUEN** [comment]
This is the current implementation:
On supported browsers:
![chrome](https://cloud.githubusercontent.com/assets/2461812/16954477/97a688be-4e03-11e6-8be4-b91ed5418045.PNG)
On unsupported browsers:
![edge](https://cloud.githubusercontent.com/assets/2461812/16954498/a7a4b7ea-4e03-11e6-9d1d-810f2a33598c.PNG)

PR: https://github.com/dhowe/AdNauseam/pull/294
Oops, I didn't know @mushon has also been working on this at the meantime.

I've changed `install.png` to SVG format because I thought I was gonna need to replace it with every supported browser icon. Rather than installing and using various photo editing tools to extract the image I decided to make it programmatically by using SVG format. 

I will try to make the best of our effort to combine our changes and make it better :+1:

**Comment by mushon** [comment]
Sorry for missing this Cyrus. 
Please check the note I left with the commit. I think it should be quite straight forward to integrate our work as I built the button frame with CSS (rather than svg). Let me know if you need my further input.

**Comment by CyrusSUEN** [comment]
Thank you @mushon. This has been handled and fixed. Closing

**Comment by mushon** [comment]
No, thank you. :)
