### ISSUE TITLE
Incorrect mouseover in Firefox

### ISSUE THREAD

**Issue by oscaryfish** [dhowe/AdNauseam#311]
![screen shot 2016-07-26 at 4 09 08 pm](https://cloud.githubusercontent.com/assets/20669777/17153967/fad7300c-534c-11e6-825e-85af146ba2e7.png)

FF OSX 47.0.1
ADN 2.3.1

**Comment by dhowe** [comment]
verified

**Comment by CyrusSUEN** [comment]
Fixed: https://github.com/dhowe/AdNauseam/pull/315

Chrome and Opera are not affected by this issue because they use `chrome.runtime.getManifest()` API to access the extension name from `manifest.json` https://github.com/dhowe/AdNauseam/blob/master/platform/chromium/vapi-background.js#L44

The Firefox version of uBlock Origin has not yet switched to Firefox's newer WebExtension API, which will be compatible with Chrome extension API, and the line is hard-coded for the moment: https://github.com/gorhill/uBlock/blob/788ff0a21f8b6ab20825c6a81d46a0efa3ce4881/platform/firefox/vapi-background.js#L75
