### ISSUE TITLE
Option to block Flash and other plugins, e.g., Silverlight, etc (click-to-play) 

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#319]
We may also want to block sites from saving to local storage, and thus potentially bypassing our cookie management.

So perhaps something like this fiddle (perhaps accessible initial on our first-run page?)

![screen shot 2016-07-31 at 3 18 35 pm](https://cloud.githubusercontent.com/assets/737638/17278746/1a4f90f8-5732-11e6-97e9-8b7617838150.png)

https://jsfiddle.net/482f2n6k/2/embedded/result/

**Comment by dhowe** [comment]
I've bumped the priority here as this is wreaking havoc as well with our memory benchmarks...

**Comment by CyrusSUEN** [comment]
I did a preliminary test result (main difference is that I didn't wait for 2mins for each test but capture the memory usage right away) with and without Flash plugin by going to `chrome://plugins/` page to disable the Flash plugin.

With Flash:
![image](https://cloud.githubusercontent.com/assets/2461812/17781276/472c4102-65a1-11e6-97b4-6444ee66d31f.png)


Without Flash:
![image](https://cloud.githubusercontent.com/assets/2461812/17781261/39409eb2-65a1-11e6-8508-2931a24c356d.png)

Saw a 300MB of memory reduction.
And the flash process only took 250MB this time (perhaps because I didn't wait for 2 mins)

**Comment by CyrusSUEN** [comment]
Starting at version 53, Chrome will not load any flash content smaller than 5x5 pixel in size.
https://groups.google.com/a/chromium.org/forum/#!msg/chromium-dev/QL2K4yFVg_U/vj44YWOaAwAJ
http://www.ghacks.net/2016/08/10/google-chrome-block-flash/

Besides from switching off Flash manually in the browser, I've also found [an extension](https://chrome.google.com/webstore/detail/flashcontrol/mfidmkgnfgnkihnjeklbekckimkipmoe/related?hl=en) which will detect and disable Flash content and [its source](https://clients2.google.com/service/update2/crx?response=redirect&x=id%3Dmfidmkgnfgnkihnjeklbekckimkipmoe%26uc&prodversion=32).

**Comment by dhowe** [comment]
What we need is a way to replace flash content with a click-to-play button.
Several extensions exist that do this already...

**Comment by dhowe** [comment]
@CyrusSUEN please update this ticket

**Comment by dhowe** [comment]
should consider whether we want to go down this path, or perhaps leave it to another extension (same with social media buttons, and perhaps 3rd party-cookies)

**Comment by Madis0** [comment]
Most plugins are deprecated and Flash will be next year.
