### ISSUE TITLE
Test on Chrome OS

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#333]

**Comment by CyrusSUEN** [comment]
I cannot get a Chrome OS because it is not freely available on Internet but [Chromium OS](http://arnoldthebat.co.uk/wordpress/chromium-os/).
Chrome OS and Chromium OS are similar though. 

ADN works as expected on Chromium OS 54 as it would on a regular OS as a browser extension:
![screenshot 1](https://cloud.githubusercontent.com/assets/2461812/17560106/5cf7c0e6-5f53-11e6-82dd-7c8ce759723c.png)
![screenshot 2](https://cloud.githubusercontent.com/assets/2461812/17560107/5d01f9b2-5f53-11e6-8ed5-7754871ba18a.png)

Closing the ticket.
