### ISSUE TITLE
Hidden DOM elements not getting collapsed

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#363]
Ad at top of page is being hidden, but not collapsed in the DOM (as it is in uBlock)

https://thepiratebay.org/search/mr%20robot/0/99/0

![screen shot 2016-09-02 at 7 55 26 pm](https://cloud.githubusercontent.com/assets/737638/18203104/3c0df32c-7147-11e6-8de1-6609cdd16593.png)

**Comment by cqx931** [comment]
The issue is caused by multiple layers of iframes, the iframe of the ad is successfully collapsed, but not the other iframes that wrap it up.

https://github.com/dhowe/AdNauseam/pull/364
By adding the filter "##iframe[src*="thepiratebay.org/static/ads"]", this problem can be solved only within piratebay but not in other cases where multi-layers of iframes exist. 

What I can come up with is to make some changes in hideElements in contentscript-end.js, but is multi-layers of iframe very common? If yes, it shall worth the effort to handle the case separately.

**Comment by dhowe** [comment]
This is a good fix for now. Lets watch to see if the problem recurs elsewhere, then we can either fix it more generally or submit a ticket to ublock...
