### ISSUE TITLE
Update Chinese locale files

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#379]
To match what is generated from:

`$ ./tools/make-locales.sh`

Unless you specify otherwise, the (english) file to check against will be written to: 

`/tmp/_locales/en/messages.json`

When finished commit the changes and upload them to  [crowdin](https://crowdin.com/project/adnauseam) as well.

We also need to check for (and encourage) other translations in crowdin...

@CyrusSUEN please help @cqx931 with the crowdin workflow as needed, and update [this question](https://github.com/dhowe/AdNauseam/wiki/Handling-languages,-locales,-and-translations) on the Dev Wiki.

**Comment by CyrusSUEN** [comment]
So i've talked and explained our Crowdin workflow to @cqx931 . 

To make it clear for future collaborators, I'm explaining it here:
We sometimes make the first hand changes of adnauseam.json on Github. But for volunteers they will need Crowdin as the platform for exchanging and contributing the translations.

Chrome browser only accepts `messages.json` as the locale file and we share a lot common locales with uBlock Origin's. We make our unique `adnauseam.json` and its English version will be the source language on Crowdin for translations.

When managing AdNauseam Crowdin project (with Crowdin Manager permission)
1. Sync the English version of Crowdin project source language `adnauseam.json` as close as possible with the one on Github
![1](https://cloud.githubusercontent.com/assets/2461812/18377999/cdc54c16-769c-11e6-89df-b432a28c1bda.PNG)

2. Make and approve translations on Crowdin 
3. Build AdNauseam project so that it contains only the latest approved translated strings
4. Download the latest Crowdin zip build file
5. Run command from locale ADN git repo `$ tools/import-adn-crowdin.sh && tools/make-locales.sh`

The last step is to import and incorporate various `adnauseam.json` files in different language it with the uBlock Origin `messages.json` to make a `messages.json` for AdNauseam.

**Comment by dhowe** [comment]
Please view (and check) the updated instructions [here](https://github.com/dhowe/AdNauseam/wiki/Handling-languages,-locales,-and-translations)
