### ISSUE TITLE
Question: should we be blocking beacons even when paused on a page/site ?

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#398]
uBlock does

**Comment by mneunomne** [comment]
It seems that we are already blocking it.
Apparently uBlock used to call beacons as beacons on the logger. But now it is just "ping".

https://www.reddit.com/r/uBlockOrigin/comments/bnga2j/block_web_beacons/
print from the reddit discussion:
![](https://i.imgur.com/6jiyZFG.png)

Now we can see the same url requests but instead of "beacon" it is "ping"

![beacons](https://user-images.githubusercontent.com/4967860/122963965-13226900-d387-11eb-8331-143b38f5d674.PNG)
