### ISSUE TITLE
Test Chrome version as Firefox WebExtensions

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#421]
the Chromium version should now run on WebExtensions releases (current FF versions), but 
we have to add the 'gecko' tag to manifest.json which is specific to Firefox:
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/applications

After that, testing should be simple:
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Porting_from_Google_Chrome

Next,  we should upload the "WebExtensions" version to AMO (they're currently accepting them for review).

**Comment by leoneckert** [comment]
I tried this today. After adding the gecko entry in manifest.json, i was still not able to install the Extension via the normal Firefox>Add-Ons Menu:

<img width="1228" alt="screen shot 2016-10-11 at 20 54 49" src="https://cloud.githubusercontent.com/assets/14130931/19293778/284b8e9a-8ff5-11e6-95cd-0d516726431a.png">

But I could install in via the temporary debugging pane (`about:debugging`), as described in https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Temporary_Installation_in_Firefox:

<img width="1232" alt="screen shot 2016-10-11 at 20 54 59" src="https://cloud.githubusercontent.com/assets/14130931/19293788/48217e32-8ff5-11e6-81ae-dfbfc81b2383.png">

However, it didn't function, didn't hide or collect ads and the interface has bugs, too. 

<img width="1341" alt="screen shot 2016-10-11 at 20 55 21" src="https://cloud.githubusercontent.com/assets/14130931/19293797/5b654640-8ff5-11e6-976e-4932fb558ff6.png">

This is perhaps because there is still things we use that Firefox doesn't? Like `"permissions": "unlimitedStorage"`

When I try to the see the background.html console, I see these errors:
 
<img width="1240" alt="screen shot 2016-10-11 at 21 00 38" src="https://cloud.githubusercontent.com/assets/14130931/19293855/e2845f58-8ff5-11e6-9118-fd380cd8a653.png">

**Comment by dhowe** [comment]
dup
