### ISSUE TITLE
parseOnClick failing unit-test

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#438]
![screen shot 2016-09-24 at 4 56 26 pm](https://cloud.githubusercontent.com/assets/737638/18807396/0f763008-8278-11e6-9cf8-03f308be29b6.png)

**Comment by cqx931** [comment]
I am still not sure whether it is proper to add a test case where the hostname is 'https://thepage.com'.
 
I have adjusted the parseOnClick function to handle the hostname parameter in the format of "google.com", rather than 'http://google.com', because window.location.hostname is not going to return the "http://" part.

If this logic is ok, then the hostname in the test case should be "thepage.com", rather than  'https://thepage.com'.

If you do want the hostname format to be 'https://thepage.com', then I need to change parseOnClick.

**Comment by cqx931** [comment]
fixed with https://github.com/dhowe/AdNauseam/commit/54ae3fc732c499e4f724da35db7c9984f0ceb339

**Comment by cqx931** [comment]
fixed with https://github.com/dhowe/AdNauseam/commit/54ae3fc732c499e4f724da35db7c9984f0ceb339
