### ISSUE TITLE
Resources blocked from sohu.com

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#441]
Question: are we intentionally blocking js resources from the path below (via adnauseam.txt)?

```
#sohu.com
||images.sohu.com/bill/
```

we don't seem to be capturing ads from this page

**Comment by cqx931** [comment]
yes, this is intended to block the red ads you can see in the homepage. Because the script also changed the css of the div that wrap up the main content. If I simply hide those ads around, it will mess up the whole layout.
However, I also find out that this current solution will block many ads images...so I can refine it more to just block the big one in the homepage.
<img width="1119" alt="screen shot 2016-09-26 at 4 41 14 pm" src="https://cloud.githubusercontent.com/assets/3056154/18827953/113114a8-8408-11e6-8f7e-17f5c8bf24de.png">

**Comment by cqx931** [comment]
fixed in https://github.com/dhowe/AdNauseam/pull/446
