### ISSUE TITLE
Test function of EFF DNT options on Firefox and Opera

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#495]
See this entry on the FAQ for how to test: https://github.com/dhowe/AdNauseam/wiki/Testing-New-Release-Candidates#donottrack-dnt

**Comment by leoneckert** [comment]
on this, just built for FirefoxDeveloperEdition for the first time.

**Comment by leoneckert** [comment]
**Firefox**
- [x] Test that the EFF's DNT list on settings/whitelist.html is disabled whenever both disableClickingForDNT and disableHidingForDNT are disabled, and is otherwise enabled
- [x] Test that the DNT header is being sent correctly for all requests (including Ad visits) if either disableClickingForDNT and disableHidingForDNT are enabled (and vice versa)
- [ ] Test that ads from DNT-respecting sites are not hidden and/or clicked, when each of the 2 DNT settings is enabled, and that they ARE hidden and/or clicked when each setting is disabled. <- I can't verify because there were simply no ads on these sites.

**Comment by dhowe** [comment]
Disable auto-updates, then temporarily add some site with ads (and blocking) to the DNT list in uAssets, then test, then remove it without committing. We need to check:
-[ ] that ads are no longer hidden
- that no-blocking occurs at all
- that, if an ad was already collected, but not yet visited, when DNT was enabled, that it is not visited after
- that, if the DNT options are disabled, then hiding, blocking, visiting again occurs as usual

**Comment by leoneckert** [comment]
Okay, it either does not work, or I am missing something. Here is what I did:
1) in `/AdNauseam/src/js/background.js` I declare `autoUpdate: false`
2) in `/uAssets/thirdparties/www.eff.org/files/effdntlist.txt`, I append:
```
@@||nytimes.com^$third-party
@@||cnn.com^$third-party
```
3) I run `tools/make-opera.sh` in AdN (tried with and without running `tools/update-ublock0.sh` in uAssets before).
4) I double check that in the build folder the appended websites are still in the effdntlist.txt.
5) Load extension to Browser.

-> then I go to nytimes.com or cnn.com, but it still hides and collects ads. 
I could not find out if maybe the actual whitelist that is used comes directly from src: https://www.eff.org/files/effdntlist.txt as opposed to assets/thirdparties/www.eff.org/files/effdntlist.txt ?

**Comment by dhowe** [comment]
Why change it in background.js -- that only contains the default for new installs ?
Just use the UI

**Comment by dhowe** [comment]
on hold
