### ISSUE TITLE
Click-to-inspect requires two clicks after drag

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#529]
To recreate:
- open vault
- drag ads around
- click to inspect an ad (only appears to work on 2nd click)

**Comment by leoneckert** [comment]
it does have to do with the real time dragging. I solved one problem, and created this one without noticing before you told me now. 

There is two ways of dragging the ads. Either you (1) click next to them and drag or you (2) click on and ad and drag. 
I noticed that when doing (2) and releasing mouse after dragging it automatically goes into inspect mode for that ad which was really irritating. I solved that one, so that now, if doing (2) it actually should only take one click afterwards to inspect. 
However, I didn't think about what you are noting here, so I have to distinguish between dragging ON ads and dragging OFF ads to handle this. I just looked into it, and it doesn't sound too hard, but I couldn't solve it right now. Will get back to it next time.

**Comment by dhowe** [comment]
Clicking on an ad brings up the inspector. Clicking off the ads allows for drag-n-drop.

**Comment by leoneckert** [comment]
you mean that's how it should be? but then when you collect a lot of ads and zoom into them, you wouldn't be able to drag through them anymore...

**Comment by dhowe** [comment]
@cqx931 please verify and close if finished

**Comment by leoneckert** [comment]
oh sorry @dhowe i forgot to mention that this now also allows both to drag ON and OFF the ads, and in both cases it only takes ONE click to go into inspect mode

**Comment by dhowe** [comment]
👍
