### ISSUE TITLE
Detect and warn about ABP/uBlock on install

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#546]
@cqx931 can you check if this is possible? we need to know whether abp and/or ublock are a) installed AND b) enabled... if so, we give a warning

first try is to do it through chrome APIs -- if this doesn't work, we may be able to check for the presence of certain objects in the environment...

see https://stackoverflow.com/questions/36192816/detect-if-another-chrome-extension-is-installed

**Comment by cqx931** [comment]
Just checked chrome APIs and I have managed to detect whether adp or uBlock are installed and enabled through their id.

**Comment by dhowe** [comment]
ok, so can we check this and display a warning on the firstrun page?

**Comment by dhowe** [comment]
yes, you can create a new Notification at the top of shared.js

**Comment by cqx931** [comment]
Does it mean that it will be part of the whole notification system that not only shows in the firstrun page, but also in menu,vault and settings later?

If that's the case shall we use setEnabled function from chrome APIs to disable other extensions? (Instead of a 'Reactive' button, here we need a 'disalbe' button).
https://developer.chrome.com/extensions/management#method-setEnabled

**Comment by dhowe** [comment]
> Does it mean that it will be part of the whole notification system that not only shows in the firstrun page, but also in menu,vault and settings later?
> 
correct, however this is the only notification which shows on the firstrun page
> If that's the case shall we use setEnabled function from chrome APIs to disable other extensions? (Instead of a 'Reactive' button, here we need a 'disalbe' button).
> https://developer.chrome.com/extensions/management#method-setEnabled

No, I don’t think that we should disable other extensions. Instead, our button, which can be called ‘deactivate’, can just be a link to the page where the extension are listed: chrome://extensions/

**Comment by cqx931** [comment]
ok,  then my thoughts of implementing this is : 
1.add a property called `adBlockersEnabled` after `firstInstall` :
https://github.com/dhowe/AdNauseam/blob/master/src/js/background.js#L49
2.And use that as the prop attribute for the notification in shared.js
3.We can check this attribute on firstinstall, but since the users are going to deactivate other extensions  in chrome://extensions/, when should we check this afterwards?

**Comment by dhowe** [comment]
> On 26 Oct, 2016, at 3:43 pm, cqx931 <notifications@github.com> wrote:
> 
> Does it mean that it will be part of the whole notification system that not only shows in the firstrun page, but also in menu,vault and settings later?
> 
> 
Correct
> If that's the case shall we use setEnabled function from chrome APIs to disable other extensions? (Instead of a 'Reactive' button, here we need a 'disalbe' button).
> https://developer.chrome.com/extensions/management#method-setEnabled <https://developer.chrome.com/extensions/management#method-setEnabled>
No, I don’t think that we should disable other extension. Instead, our button, which should be called ‘deactivate’, can just link  to the page where the extension are listed: chrome://extensions/ <chrome://extensions/>

**Comment by dhowe** [comment]
we don't need any new property in background.js
we check it in on firstrun.js and on the main settings page
and then, we don't let the user turn on any features (hide,click,block) until it is disabled

**Comment by cqx931** [comment]
but isn't it in core.js that we broadcasting all notifications to non-background pages? So the adblock check shall be in core.js?

**Comment by eagerstudent** [comment]
yes, firstrun.js sends a message to core.js on load, asking about this one notification, core.js responds and firstrun.js shows the notification if needed

**Comment by cqx931** [comment]
[Here](https://github.com/dhowe/AdNauseam/pull/561) I have got the warning message on first-run page, but there are two things I am not sure about:
1.Currently I have used a callback-chain to VerifyAdBlocker in dashboard.j  verifyAdBlocker->getNotifications->LoadDashboardPanel... but I'm not sure whether this is proper or there is a better way to achieve this.
2."If there are other ad blockers enabled, don't allow user to select hide/click/block."
I didn't implement this part yet, as I'm not sure about the exact effect.
In my opinion, it should be more obvious and easier to implement, if we add a 50% opacity black layer on top of first-run page rather than just disable every button.
And if the user enable other adblocker after installing AdNauseam? Will we disable all functions for that as well?

**Comment by dhowe** [comment]
Let me take a look at dashboard.js -- @mushon, your thoughts on 2 above?

**Comment by cqx931** [comment]
Updated the vAPI.openBrowserPage() function in vAPI.client for chrome.
https://github.com/cqx931/AdNauseam/commit/a7e0bbc0de88f5816071633a93e04420732eb9e2
Still need to do this for firefox.

**Comment by cqx931** [comment]
A brief summary about the current stage of this function at this stage:
1.The function is now live in chrome (without disabling other function if any adblock is detected)
2.The function is not implemented yet in Firefox, I didn't find any useful information about this from Mozilla [Add-on SDK](https://developer.mozilla.org/en-US/Add-ons/SDK), so we might need to check "the presence of certain objects in the environment..." for firefox

**Comment by dhowe** [comment]
👍

**Comment by cqx931** [comment]
I missed the documentation for WebExtensions in the previous research, now I get verifyAdBlocker working in firefox by using ` AddonManager`. Please check https://github.com/dhowe/AdNauseam/pull/604

**Comment by mushon** [comment]
Sorry, I’m currently traveling. Will be back in the studio next week and would take a look if still relevant.

**Comment by dhowe** [comment]
we don't need to do anything other than issue the warning
