### ISSUE TITLE
DNT whitelist checkbox not updating correctly

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#552]
to recreate:
1) go to settings page, enable Hiding and Clicking
2) enable both DNT checkboxes  
3) disable Hiding and Clicking
4) go to whitelist and notice the DNT list is still checked

![screen shot 2016-10-27 at 8 38 14 pm](https://cloud.githubusercontent.com/assets/737638/19767508/cffe8826-9c85-11e6-97c9-85b6d2121168.png)

**Comment by cqx931** [comment]
The checkbox in whitelist doesn't seem to be correctly update after the change in settings page.
Currently it only response to the setting from the first set-up, but not from any changes afterwards.

**Comment by cqx931** [comment]
the problem is when the user uncheck Hide/Click/Block, the corresponding subgroups only get refreshed within the userinterface, but not stored in the usersetting.(which I think should be right...)
https://github.com/dhowe/AdNauseam/blob/dnttest/src/js/adn/options.js#L120

so I changed the effListEnabled in messaging.js, so that it also consider the status of hidding/clicking.
https://github.com/dhowe/AdNauseam/pull/556/commits/68686654f4a0557763d1b7cf704191f90a0866d8

**Comment by cqx931** [comment]
fixed
