### ISSUE TITLE
Detect mobile versions and disable DNT options...

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#722]
DNT is not valid as yet for mobile...

**Comment by cqx931** [comment]
Can users install adnauseam on mobile? What is the exact case here?

**Comment by dhowe** [comment]
they can, on firefox, but mobile is not part of the EFF's DNT standard, so we need to a) detect when on mobile, b) remove the options from interface, and c) treat as if both DNT options are false (disableHidingForDNT=false, disableClickingForDNT=false)

**Comment by cqx931** [comment]
If the case is only on firefox so far, we can detect whether the user is on mobile only for firefox for now.
To detect mobile, the most obvious way is to use navigator.userAgent.match, but since users can have extensions on their mobile, this could be easily changed...

Another way to do this for firefox is to detect whether the object [NativeWindow](https://developer.mozilla.org/en-US/Add-ons/Firefox_for_Android/API/NativeWindow) exist, as it is only available on Firefox for Android.

**Comment by cqx931** [comment]
Any feedback on this? @dhowe

**Comment by dhowe** [comment]
yes, lets put this on hold pending the switch to web-extensions...

**Comment by cqx931** [comment]
NativeWindow should be safe to use for both web-extension and old firefox addon

**Comment by cqx931** [comment]
Please check: https://github.com/dhowe/AdNauseam/pull/1075
