### ISSUE TITLE
Ad visit failing (adn extracts invalid targetUrl)

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#736]
PAGE: http://doodle.com/poll/c42d2b7kyvv5ag5h

![screen shot 2017-01-11 at 7 10 20 pm](https://cloud.githubusercontent.com/assets/737638/21846359/c45b217c-d831-11e6-9933-800d5ad634a1.png)

CORRECT (Final) target: http://www.manks.com/main/modern/showmodern.asp?cat=TABLES

OUR targetUrl: https://doodle.com/aclk?sa=l&ai=CoMhn_xF2WLidJsfV2AS01qWwDubOsMZH2p3n_0_Ajb…43337&adurl=http://www.manks.com/main/modern/showmodern.asp%3Fcat%3DTABLES

ACTUAL targetUrl: https://googleads.g.doubleclick.net/aclk?sa=l&ai=CZksTLRJ2WIvKBoTZ2ATs7pmwD-bOsMZH2p3n_0_AjbcBEAEghNm3CGDZAqABkuaT7gPIAQKpAioZoXriToE-qAMByAPJBKoEf0_QsD2b9fkfi8FkB4H8JXmeFai6cWMlozsWCt77NheMpE0sNnLX6HVo3USNcqdFEDQSiwCwtidXEJW2yDBc-_fJ6f7W2So-pex_dZqzF0mIRa9pPo6en-rKfA86R89hX0Pbo6SeJ3Qq9jf-VC9lc-g3r5zdz5VurJLjFPav0-WgBgKAB9aZ7BGoB6a-G9gHAdIIBQiAYRAB&num=1&sig=AOD64_1WiS6saCyT0QGYjVTnF_xN0VPFYg&client=ca-pub-8391840451743337&nm=2&nx=114&ny=454&mb=2&bg=!BwSlBBxEScNfwiOT33ECAAAAPlIAAAATmQF9noghQ3z1DrpK8vqimV8Yup_jfazUk_n72j8Zw-kIqH7N-nn5ryN27TtKCKBWg0bKoYpLMM6BfREMZPbn64S8yAM8wZYWvUPPOrrFDQsXC1qJJZNOjZAB8yt2Im5n2EWPC5MBzVIiSFkIVUbWAKDbjECwfR76g_wkcwtE9Krqif8RfOmNRSVDTaLQruM40M9VOEeamfMlfWjt2u-xtRaDS5GHby2OqhngNOAHMSe4oeSAnMKCkV1n1gnzov71NsoaDbSd-v3gK-qCzS-_sMiTo7jE4rRiJmsBS77KvBc0UXVjdBWgD-s9dwk76I1LFiF6Izv_GWK6gWHYQojYEKQdBjohFrMj54hxxlH_xoykg111XuO9gIXq2UNm55EKLHqDQYlBoDmc8yMkkisEzAzoKAEa5rOihV2kBVr8KBz-68rMS35OtJBxfNAM-TUnpX51txl47jM6JAV_4k0cFXTcQ8JJgDPoTJRnMW2SSl-vZ-1T-5adKHUsbmGu6xIC&adurl=http://www.manks.com/main/modern/showmodern.asp%3Fcat%3DTABLES

**Comment by cqx931** [comment]
I can't see this ad when I search for 'nytimes'. What's the target when you click on the real ad?

**Comment by dhowe** [comment]
Not sure

**Comment by dhowe** [comment]
Another case (from the same page):

FINAL: https://www.ixl.com/promo?partner=google&campaign=1048&adGroup=worksheets

ADN: https://doodle.com/aclk?sa=l&ai=CMmOuFCB2WLD6F4bl2QT93a-ACNzk9tpFiePnh8MCwI….ixl.com/promo%3Fpartner%3Dgoogle%26campaign%3D1048%26adGroup%3Dworksheets

CORRECT: https://googleads.g.doubleclick.net/aclk?sa=l&ai=CMmOuFCB2WLD6F4bl2QT93a-ACNzk9tpFiePnh8MCwI23ARABIITZtwhg2QKgAaPS2_wDyAEDqAMByAPIBKoEgwFP0O3sm_aXToyJT9mpBMfD0AsFdBUFJ5PkigMK0LYKkZ8zvcyioMFzkdlFfr0SEQEaGVcngoAHeACIAJIjS2CPleait5xzTO8hm3yTfj-p6aNsy2K_qE7SOnZyTvBJykhKcro9bnfLxyBPMajp9AuXRb1Ae8JKHavaYjsGMRqvNyoiJqAGA4AHxa2kA6gHpr4b2AcB0ggFCIBhEAHYEwg&num=1&sig=AOD64_3bV9al41UwMS-uAgYynSopfhnipQ&client=ca-pub-8391840451743337&nx=77&ny=267&mb=2&bg=!q6ilqLBEtvi5-25baycCAAAAYFIAAAAOmQF9Mh10hLReG-CRDSucpKKdFPCQlnLKJNdj_GUcg9XeEvFMA78z9pWxG2C6YlbSWeVMphNeuE7aw1bjTV-9zWKLgS90SkCuP1qt26MB0j6X4VdAiaMoqCLiCvN9Hxd_RQXuGrMjTGui2Yg9a3TzwpTGBnLcS8PMMrZHcUVLlIOTT1nSRpgP_Lgqts3UUTqn4zSMSpAQ_7s_8D285J01ABnyTSK8lT5OOneoGQbtbbfxfFSXGRgGBoYrYm9RMXus9GHgQJs0SM0HYg6yfOfhk-AfKGjpdqPXoAUNSVoYDP3F6GaOg7mZNjtDT0B-LQQfB4WEUT5vz6UWmh7hcR5T9ue0R06ZchNbnIVBpY-b-QpawBj3n3WYnUzRsvUgpvmCAHcCurAbp1Vw38P6x7LJ0PwaNh6-eWsKWpMvpiSJnURsAUPKMcmfbFkSm10H6YUvyccg9GwrxurPtb-NDwgbitfN24pdWLtdsAuxXE0QuBcszvduRecDDY2nNDL_gCdh&adurl=https://www.ixl.com/promo%3Fpartner%3Dgoogle%26campaign%3D1048%26adGroup%3Dworksheets

```
{
  "attemptedTs": 0,
  "attempts": 0,
  "contentData": {
    "height": 600,
    "src": "https://tpc.googlesyndication.com/simgad/14043542512161025506",
    "width": 160
  },
  "contentType": "img",
  "current": true,
  "errors": null,
  "foundTs": 1484136468679,
  "id": 7,
  "pageDomain": "doodle.com",
  "pageTitle": "Doodle: SM8401/3 Research Seminars I/II, Sem B, 2016-17",
  "pageUrl": "http://doodle.com/poll/c42d2b7kyvv5ag5h",
  "resolvedTargetUrl": null,
  "targetDomain": "doodle.com",
  "targetHostname": "doodle.com",
  "targetUrl": "https://doodle.com/aclk?sa=l&ai=CMmOuFCB2WLD6F4bl2QT93a-ACNzk9tpFiePnh8MCwI….ixl.com/promo%3Fpartner%3Dgoogle%26campaign%3D1048%26adGroup%3Dworksheets",
  "title": "Pending",
  "version": "3.0.4",
  "visitedTs": 0
}
```

**Comment by dhowe** [comment]
The actual ANCHOR and enclosed IMG are as follows:
```

<a id="aw0" target="_blank" href="https://googleads.g.doubleclick.net/aclk?sa=l&amp;ai=CdGaI1iJ2WMOwBY312ASk8ZPgA9zk9tpFiePnh8MCwI23ARABIITZtwhg2QKgAaPS2_wDyAEDqAMByAPJBKoEf0_QfhPbCbNxrXhpkYCEVkeA1WvYKYsLsEKo4Zsx66qk5GctEtmXYXIuEsZFM4G5g403YteInRaJVh1tYyN0d-w9nTD42CIsUo4w1QyuZrUkTi9DqGLQNuBPZELEAc10Z09e4m5r1v6YDeScjs7Pmq3qWXetK9nvskg-cDYM6cigBgOAB8WtpAOoB6a-G9gHAdIIBQiAYRAB2BMI&amp;num=1&amp;sig=AOD64_0Oh5bzBZMpGoeTAcDe89c6nqr-IQ&amp;client=ca-pub-8391840451743337&amp;nm=3&amp;nx=121&amp;ny=159&amp;mb=2&amp;bg=!w8ClwNhEk-VJKJ54tGECAAAAPVIAAAAPmQGBkIl1Pt-cA9gmkG7D4yQ05buq0XilECdoKUFTS3Zh7qHnSnmdZZSgJP50andbidt4NHbvxbAO8xIQim5R3383FWS1kpqfaqh6WhPeqR9AURDDjMb7jY7j5JyvoZk-Mu-97BQMQ7S2ng8bTkwRjoaVzYJ1daWu-UdLqoYs55MQj9FAoFVIjvaTYJpGkGyy2zBK8lzSoqzPWtXobjjNfCsoveNzwyOTfPJnBDD82_VnNoafrgGfXtwpQ8RXhjuW94Y2FWllOtO3wppGbxw38YBePG-Hmctwwp73_zY-YFhO3eFNCcv5fjeSTSSc15CXgK6DiV1zIuYqcEDcoLeOeVFgh1Ut5EXToxjZw6MHJAS0OPzUnEFTbDBwBnfgDAoYXpqIOU4fNLJ1enEutPZKhzEt0daUkYjXL8scU3E41R6J2jGdjVhXkW6_7Ew79QvUSRElEWH313th99RXz2-hzn6rqExCOyRtXj-zzsNKGFqV-G6Yhpca5UGj9BeYdKO5Efa60A&amp;adurl=https://www.ixl.com/promo%3Fpartner%3Dgoogle%26campaign%3D1048%26adGroup%3Dworksheets" data-original-click-url="https://googleads.g.doubleclick.net/aclk?sa=l&amp;ai=CdGaI1iJ2WMOwBY312ASk8ZPgA9zk9tpFiePnh8MCwI23ARABIITZtwhg2QKgAaPS2_wDyAEDqAMByAPJBKoEf0_QfhPbCbNxrXhpkYCEVkeA1WvYKYsLsEKo4Zsx66qk5GctEtmXYXIuEsZFM4G5g403YteInRaJVh1tYyN0d-w9nTD42CIsUo4w1QyuZrUkTi9DqGLQNuBPZELEAc10Z09e4m5r1v6YDeScjs7Pmq3qWXetK9nvskg-cDYM6cigBgOAB8WtpAOoB6a-G9gHAdIIBQiAYRAB2BMI&amp;num=1&amp;sig=AOD64_0Oh5bzBZMpGoeTAcDe89c6nqr-IQ&amp;client=ca-pub-8391840451743337&amp;adurl=https://www.ixl.com/promo%3Fpartner%3Dgoogle%26campaign%3D1048%26adGroup%3Dworksheets">

  <img src="https://tpc.googlesyndication.com/simgad/14043542512161025506" border="0" width="160" height="600" alt="" class="img_ad">
</a>
```

**Comment by cqx931** [comment]
I still can't reproduce this... Even if I copy paste the above code and create a page to let adnauseam to collect the ad. 
Though what interesting is, when I inspect element, this is what chrome renders from the code above:
![image](https://cloud.githubusercontent.com/assets/3056154/21849465/e4cad5ba-d840-11e6-9153-58b8caf2c77a.png)

Do you see this as well?

**Comment by cqx931** [comment]
Just see this failing case from http://www.mrfreeat33.com/its-not-about-the-money-rent-versus-buy/
The target link is not shortened in my case, but the domain name is also replaced, though this time it fails to get the correct domain name and returns "undefined".

And this one is also from google ad.
```
  "id":13,
         "attempts":3,
         "visitedTs":-1484223085526,
         "attemptedTs":1484223085521,
         "contentData":{
            "src":"https://tpc.googlesyndication.com/simgad/7744173245718711372",
            "width":728,
            "height":90
         },
         "contentType":"img",
         "title":"Failed",
         "resolvedTargetUrl":null,
         "foundTs":1484223060326,
         "targetUrl":"https://undefined/aclk?sa=l&ai=C8Py0UnJ3WMnHIcGT9AWUvaTAC9np0_VH-pC17LYDsb26wcAEEAEggcHwIWDZAqAB94Ha1APIAQKoAwHIA8kEqgSnAU_Qx7qdrdrQZsn87teqzLAJJIPNFbpeEDxbUtp0Fwi43Y-N493pvcXJcwXbAvGV96pBMLfrTTThgMP6aOgbku9igR9AiLLMAT1UUifZTsHsPfARv0PREZN8AHPbnuYLeuwsa_2yi55nUKAXm-iP8aHXuZWS-MdhF7WHV829KDXRZh6o0-5yAxS71FnVjaRZkwH9l1Gw4U_gVURa0qJNT8mW0aohiriooAYCgAeagaMzqAemvhvYBwHSCAUIgGEQAQ&num=1&sig=AOD64_0VI_cDweBZ19o4xgC3BL24Nl74sQ&client=ca-pub-0160058262814943&adurl=http://global.qlik.com/us/landing/go-sm/qlik-sense-desktop/brand-display%3FsourceID1%3Dgoogle%26Campaign_Type%3DDisplay%26KW%3D%26k_clickid%3D_kenshoo_clickid_",
         "pageTitle":"http://www.mrfreeat33.com/its-not-about-the-money-rent-versus-buy/",
         "pageUrl":"http://www.mrfreeat33.com/its-not-about-the-money-rent-versus-buy/",
         "errors":[
            "0 () error",
            "0 () error",
            "0 () error"
         ],
         "current":true,
         "pageDomain":"mrfreeat33.com",
         "version":"3.1.20",
         "targetDomain":"",
         "targetHostname":"undefined",
         "requestId":"19238"
```

The real url should be:
https://www.googleadservices.com/pagead/aclk?sa=L&ai=C0rfKqHN3WP-QMYTz2ATP7IqYDtnp0_VHgp-17LYDsb26wcAEEAEggcHwIWDZAqAB94Ha1APIAQKoAwHIA8kEqgSuAU_Q7hQusgL6q1pkPqKAR1J1iIeJI9pk75Za6PHAzv2ORLdwvYkrIsjtC7WMNTA-8BfHKkeCX8mIusJyd9acvMpXc2tLWE_3w7nxn58BFXKYgtRLSiary_m6Ib5QyHj9PCrcJh9tCBYSGSk_pXIP9KXfhrqsJiXRU0lsPb3jzOOsqxrF4j_jne49X92WtqH_B-UIexyrS1TmwZZsSq3skDyCMwLWUo8tmqKlGc5_VogGAaAGAoAHmoGjM6gHpr4b2AcB0ggFCIBhEAE&num=1&cid=CAASEuRo-68N88FSGW7Pt4L91mp-CA&sig=AOD64_0e0vbdYQbseq5PGDOJI1KS5pCqMg&client=ca-pub-0160058262814943&nm=2&nx=222&ny=36&mb=2&bg=!6eql6vJEj7d_NPQEOpoCAAAAPVIAAAATmQGE_jUKTSzISpSxIIX6iTkSOvgjmutx91Se83B3g_q-BLRtz7KwkkzzDfWexwy_YYLMGgcEewPMOFi-7TnZ_1nkn8QODQS0oOcj-ZWEmHxfT_CRLqlYg6d4Yj9AF88W0T_2tmk3_fSRokIMRuScNG49fVSRLqgREjdXNxynu0k3Ylf1wGb65H0oCshQlACtZ4kooJZppz00lC5qPvNWOZQqEtf_nhfzTniDNEvrHMaiPsTKmJrk1OX-gGA6tCSFzSATOsN-RGSLTWtiic1Tn0JfyujWm0w5VY-w9KpeYVmJvoeQrMfnklZUYnEtS0_R1yiGMX4sOIbpM1q8xhaghPW4Xxqy3NTVC4vboGfr6FUPpXm6k_duQGOi2b8-uPTwuikse-bzvhaH04Kk1_P5ISVTs5j1pLtu--96UvR6XZWr4qPOsHZbF8zYY4T6k16ep6OPMXazUvvN7vI2lf7ikTB1QYo0VRIbBWuxVKAAwQMdwyAtFPjLPeXURVn4RR5rYAdMzz5bLg&adurl=http://global.qlik.com/us/landing/go-sm/resources/gartner-magic-quadrant-2016-display%3FsourceID1%3Dgoogle%26Campaign_Type%3DDisplay%26KW%3D%26k_clickid%3D_kenshoo_clickid_

![image](https://cloud.githubusercontent.com/assets/3056154/21889721/55246a14-d905-11e6-9b5f-677768057f60.png)

**Comment by cqx931** [comment]
But I just saw this ad once and it doesn't show up again...

**Comment by cqx931** [comment]
The url seems to be with no domain name in the real html. What we see in the dom could be generated from the browser or modified by javascript. The way I think that can solve this strange domain replacement case is to use "data-original-click-url" when it is available instead of href value.

`<a id="aw0" target="_top" href="/aclk?sa=L&amp;ai=Cw03O8Zx3WLjyG8ve2AS9srioB9Tt59tH0b3ggsYEwI23ARABIIHB8CFg2QLIAQOpAneOw7UVrmM-qAMByAPJBKoErAFP0CIAyEKNLzjqG2k8xc4IRp0O2dWcnGZCH72HPPKu1Et9g3l3ymyLvXqii-zDtLLs-WNGzrF7eax67lncM0aV3bCeNUfeRF_QZa0trEFGMX9nwuBq7aVLu0jqloVj_EyYufVbfRtRXFu7mB7VeyMW67U9ToR5CmxLXJbCXDJQltcfpAkfnLhQ6kkD0ZNvMu0qrJWENNVKyyg0nZHvF2d6Vii4wRoBpG4ZPLRfoAYDgAfy2-FiqAemvhvYBwHSCAUIgGEQAQ&amp;num=1&amp;sig=AOD64_2pg2HD3gM7Q-yB7DMEhQ80-MmWuQ&amp;client=ca-pub-0160058262814943&amp;adurl=http://www.bantaiestate.com/en/robjects.html" data-original-click-url="https://googleads.g.doubleclick.net/aclk?sa=L&amp;ai=Cw03O8Zx3WLjyG8ve2AS9srioB9Tt59tH0b3ggsYEwI23ARABIIHB8CFg2QLIAQOpAneOw7UVrmM-qAMByAPJBKoErAFP0CIAyEKNLzjqG2k8xc4IRp0O2dWcnGZCH72HPPKu1Et9g3l3ymyLvXqii-zDtLLs-WNGzrF7eax67lncM0aV3bCeNUfeRF_QZa0trEFGMX9nwuBq7aVLu0jqloVj_EyYufVbfRtRXFu7mB7VeyMW67U9ToR5CmxLXJbCXDJQltcfpAkfnLhQ6kkD0ZNvMu0qrJWENNVKyyg0nZHvF2d6Vii4wRoBpG4ZPLRfoAYDgAfy2-FiqAemvhvYBwHSCAUIgGEQAQ&amp;num=1&amp;sig=AOD64_2pg2HD3gM7Q-yB7DMEhQ80-MmWuQ&amp;client=ca-pub-0160058262814943&amp;adurl=http://www.bantaiestate.com/en/robjects.html">"
`
![image](https://cloud.githubusercontent.com/assets/3056154/21893880/eef45fe8-d917-11e6-8772-c87b952e81a0.png)

**Comment by cqx931** [comment]
Please check. It should solve similar failing cases.
https://github.com/dhowe/AdNauseam/pull/757

**Comment by dhowe** [comment]
I dont see the 'data-original-click-url' attribute on the anchor here... am i missing it?
Also, this is a relative URL, which we should be handling in the normal way, that is, taking the page (or possibly iFrame domain) and prepending it to the relative URL. So, if the page was http://amazon.com/blah/blah/foo.html, then the targetUrl should be http://amazon.com/aclk7?sa=...

**Comment by cqx931** [comment]
just updated the format of the code snippet above, you should be able to find 'data-original-click-url' more easily now.  And the target url will finally resolved to http://amazon.com/blah/blah/foo.html after the successful ad visit from the correct link.

**Comment by dhowe** [comment]
ok, merged (but lets keep an eye on this)

**Comment by cqx931** [comment]
After checking what you suggested for the iframe hostname issue, I found that there are actually two places where we are checking the targetUrl.

One is `normalizeUrl`, which is called when the ad is created.
The other is `validateTarget`, which isused in core.js and called before registerAd/visitAd/importAd.

The issue in #736 was actually caused by normalizeUrl. Because it is using the hostname of the page to reconstruct the url if the url is a relative url.
So I would argue to modify the code in `normalizeUrl`.
1.in `processImage`
if the href is a relative url and it has "data-original-click-url", it will parse the domain from "data-original-click-url" and save it as "targetDomain"
2. in `createAd`
if there is a"targetDomain" variable get passed, use this instead of the pageDomain to pass to
`nomalizeUrl`.

But then, what if the <a> doesn't has a 'data-original-click-url' attribute and the href is a relative url? How can we differentiate an ad from a page and an ad from iframe, and then get the domain of that iframe?
This could also happens to iframe text ads if we want to deal with them later.

**Comment by cqx931** [comment]
After checking what you suggested for the iframe hostname issue, I found that there are actually two places where we are checking the targetUrl.

One is `normalizeUrl`, which is called when the ad is created.
The other is `validateTarget`, which isused in core.js and called before registerAd/visitAd/importAd.

The issue in #736 was actually caused by normalizeUrl. Because it is using the hostname of the page to reconstruct the url if the url is a relative url.
So I would argue to modify the code in `normalizeUrl`.
1.in `processImage`
if the href is a relative url and it has "data-original-click-url", it will parse the domain from "data-original-click-url" and save it as "targetDomain"
2. in `createAd`
if there is a"targetDomain" variable get passed, use this instead of the pageDomain to pass to
`nomalizeUrl`.

https://github.com/dhowe/AdNauseam/pull/778

But then, what if the <a> doesn't has a 'data-original-click-url' attribute and the href is a relative url? How can we differentiate an ad from a page and an ad from iframe, and then get the domain of that iframe?
This could also happens to iframe text ads if we want to deal with them later.

A Testcase:
http://lab-lamp.scm.cityu.edu.hk/adntest/iframeRelativeTarget.html

**Comment by dhowe** [comment]
and remember that some iframe's don't even have 'domains'...

**Comment by cqx931** [comment]
this can be closed for now.
