### ISSUE TITLE
Google Ad not detected

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#747]
PAGE: http://doodle.com/poll/c42d2b7kyvv5ag5h

![screen shot 2017-01-11 at 9 12 50 pm](https://cloud.githubusercontent.com/assets/737638/21849830/ca319d18-d842-11e6-8b82-5f72098e66b0.png)

`<ins class="adsbygoogle" style="display:inline-block;width:728px;height:90px" data-ad-client="ca-pub-8391840451743337" data-ad-slot="2219348272" data-adsbygoogle-status="done"><ins id="aswift_0_expand" style="display:inline-table;border:none;height:90px;margin:0;padding:0;position:relative;visibility:visible;width:728px;background-color:transparent"><ins id="aswift_0_anchor" style="display:block;border:none;height:90px;margin:0;padding:0;position:relative;visibility:visible;width:728px;background-color:transparent"><iframe width="728" height="90" frameborder="0" marginwidth="0" marginheight="0" vspace="0" hspace="0" allowtransparency="true" scrolling="no" allowfullscreen="true" onload="var i=this.id,s=window.google_iframe_oncopy,H=s&amp;&amp;s.handlers,h=H&amp;&amp;H[i],w=this.contentWindow,d;try{d=w.document}catch(e){}if(h&amp;&amp;d&amp;&amp;(!d.body||!d.body.firstChild)){if(h.call){setTimeout(h,0)}else if(h.match){try{h=s.upd(h,i)}catch(e){}w.location.replace(h)}}" id="aswift_0" name="aswift_0" style="left:0;position:absolute;top:0;"></iframe></ins></ins></ins>`

**Comment by dhowe** [comment]
full html [here](https://gist.github.com/dhowe/419b3086748c682c3d36772ba1ab37d0)

**Comment by cqx931** [comment]
I have some problem to reproduce this issue. I am sure that if the ad in the iframe is an image, it can be correctly hidden and collected by adnauseam. So the issue must be for text ads from google. 
The chance to see a text ad is way lower than the image ads...I was able to see one when I disable the hiding but not when I enable it.

When I disable the hiding, the parser did find out the ins tag, also the div with class name "adunit" inside it. So if nothing tricky goes on... The ad should be correctly hidden if hiding is enabled.

One problem I see in this case is that, adnauseam is trying to find img inside an iframe. But because this is a text ad, it can only find out the [ google img](Ihttps://www.gstatic.com/images/branding/googlelogo/2x/googlelogo_dark_color_84x28dp.png) or other clickable button images... I have blocked these kind of requests in my latest update in blocking rules. So Adnauseam shouldn't identify them as an ad any more.
