### ISSUE TITLE
Ads with title: "Redirect Notice"

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#751]
@cqx931 can you figure out what is going on here...
I believe that the first is not a successful visit

![screen shot 2017-01-12 at 2 05 22 am](https://cloud.githubusercontent.com/assets/737638/21860457/9cce5090-d86b-11e6-9ede-5f4c0f3242b8.png)

Page: http://www.mrfreeat33.com/its-not-about-the-money-rent-versus-buy/

Ad: 
```
{
	"id": 10,
	"attempts": 1,
	"visitedTs": 1484157681327,
	"attemptedTs": 0,
	"contentData": {
		"src": "https://tpc.googlesyndication.com/simgad/9300569572577143126",
		"width": 336,
		"height": 280
	},
	"contentType": "img",
	"title": "Redirect Notice",
	"resolvedTargetUrl": "https://www.googleadservices.com/pagead/aclk?sa=L&ai=CpKHF33J2WLrmCYX02ASGz…RiN8Hifw&client=ca-pub-0160058262814943&adurl=http://www.idecorateshop.com",
	"foundTs": 1484157679786,
	"targetUrl": "https://www.googleadservices.com/pagead/aclk?sa=L&ai=CpKHF33J2WLrmCYX02ASGz…RiN8Hifw&client=ca-pub-0160058262814943&adurl=http://www.idecorateshop.com",
	"pageTitle": "It’s Not About The Money: Rent Versus Buy – Mr. Free At 33",
	"pageUrl": "http://www.mrfreeat33.com/its-not-about-the-money-rent-versus-buy/",
	"errors": null,
	"current": true,
	"pageDomain": "mrfreeat33.com",
	"version": "3.1.20",
	"targetDomain": "googleadservices.com",
	"targetHostname": "www.googleadservices.com",
	"requestId": "8271"
}
```

**Comment by cqx931** [comment]
If you can get this ad consistently, please see whether you still see this case after checking in the latest pull request. https://github.com/dhowe/AdNauseam/pull/757

**Comment by cqx931** [comment]
If I import this ad, and make adnauseam to revisit the ad by clearing the attempts. I get "400 () undefined" error. And if I visit the link, I also just see a blank page with no content. May be  the link is expired?

**Comment by cqx931** [comment]
Also for this case, it is clear that the target url should be http://www.idecorateshop.com/.
Another way that I can think of is:
If xhr.onload is triggered but the returned string is empty
try to parse the url with "&adurl=http://" if it is from googleadservices, and visit this instead?

**Comment by dhowe** [comment]
yes, the resolvedTargetUrl should be 'http://www.idecorateshop.com/', but if it is to be recognized as a 'real' click, we need to hit Google first...

my question is where do those ellipses come from in the targetUrl (...) -- is the real URL being truncated because it is too long?

**Comment by dhowe** [comment]
So it appears that Google itself is truncating the long URL (perhaps for user mouseovers?), then using the 2nd attribute (containing the full URL) for the click... yes?

**Comment by cqx931** [comment]
I just saw an ad with "Redirect Notice" on the same web page.

So what happens here is that instead of responding the real target page, what returns from google server is a page with title "redirect notice".

In this case, we definitely already hit the link from googleadservices as the visit was successful, though we don't end up with the real page.
So in 'onVisitResponse', if the parseTitle is "redirect notice", we can do the parse I mentioned above and visit the correct link from there. 
In this way, both the google link and the real link can be visited.

**Comment by cqx931** [comment]
I don't know why the ellipse can ended up in the original html code and collected by adnauseam. I didn't see a live case for this yet.
From my previous observation, I thought the link is truncated when the browser renders it and the real href shouldn't contain the ellipse. 
Because when I inspect the element in the console, the href showing is truncated, but when I hover or click on it, it shows me the whole link...

**Comment by dhowe** [comment]
Ok, back to the failed visit... does it also fail for you when clicked manually? If not, what is different?

**Comment by dhowe** [comment]
I just found another case (on the same page), where a manual click is first blocked by ublock/adn (with a blocked page warning), then, if the block is temporarily disabled, follows through to this page: 

http://www.osim.com/hkc/udivaclassic/wom/?gclid=COK9jZykvtECFUMDvAods6ENCA

The Ad:

```
 {
 	"id": 4,
 	"attempts": 1,
 	"visitedTs": 1484281666291,
 	"attemptedTs": 0,
 	"contentData": {
 		"src": "https://tpc.googlesyndication.com/simgad/11309997907269786259",
 		"width": 300,
 		"height": 250
 	},
 	"contentType": "img",
 	"title": "Redirect Notice",
 	"resolvedTargetUrl": "https://googleads.g.doubleclick.net/aclk?sa=L&ai=CijpWO1d4WLKrOYbW2AS7gLzQB…ent=ca-pub-0160058262814943&adurl=http://www.osim.com/hkc/udivaclassic/wom",
 	"foundTs": 1484281661607,
 	"targetUrl": "https://googleads.g.doubleclick.net/aclk?sa=L&ai=CijpWO1d4WLKrOYbW2AS7gLzQB…ent=ca-pub-0160058262814943&adurl=http://www.osim.com/hkc/udivaclassic/wom",
 	"pageTitle": "http://www.mrfreeat33.com/its-not-about-the-money-rent-versus-buy/",
 	"pageUrl": "http://www.mrfreeat33.com/its-not-about-the-money-rent-versus-buy/",
 	"errors": null,
 	"current": true,
 	"pageDomain": "mrfreeat33.com",
 	"version": "3.1.20",
 	"targetDomain": "doubleclick.net",
 	"targetHostname": "googleads.g.doubleclick.net",
 	"requestId": "1340"
 }
```

**Comment by dhowe** [comment]
Here is the HTML page we end up on for:  https://www.googleadservices.com/pagead/aclk?sa=L&ai=CO6DkwVh4WJaBCZLy9QXXr…160058262814943&adurl=http://www.pphk.org/concerts/festival-2017/concerts1

```
<html>

<head>
  <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  <title>Redirect Notice</title>
  <style>
    <!-- body,
    td,
    div,
    .p,
    a {
      font-family: arial, sans-serif
    }
    
    div,
    td {
      color: #000
    }
    
    .f {
      color: #6f6f6f
    }
    
    a:link {
      color: #00c
    }
    
    a:visited {
      color: #551a8b
    }
    
    a:active {
      color: red
    }
    
    div.a {
      border-top: 1px solid #bbb;
      border-bottom: 1px solid #bbb;
      background: #f2f2f2;
      margin-top: 1em;
      width: 100%
    }
    
    div.b {
      padding: 0.5em 0;
      margin-left: 10px
    }
    
    div.c {
      margin-top: 35px;
      margin-left: 35px
    }
    
    -->
  </style>
  <script>
    function go_back()
    {
      window.history.go(-1);
      return false;
    }

    function ctu()
    {
      var link = document && document.referrer;
      var esc_link = "";
      if (link)
      {
        var e = (window && window.encodeURIComponent) ? encodeURIComponent : escape;
        esc_link = e(link);
      }
      new Image().src = "/url?sa=T&url=" + esc_link + "&oi=unauthorizedredirect&ct=originlink";
      return false;
    }
  </script>
</head>

<body topmargin=3 bgcolor=#ffffff marginheight=3>
  <div class=a>
    <div class=b><font size=+1><b>Redirect Notice</b></font></div>
  </div>
  <div class=c>&nbsp;The previous page is sending you to <a href="http://www.pphk.org/concerts/festival-2017/concerts1">http://www.pphk.org/concerts/festival-2017/concerts1</a>.
    <br>
    <br>&nbsp;If you do not want to visit that page, you can <a href="#" onclick="return go_back();" onmousedown="ctu();">return to the previous page</a>.
    <br>
    <br>
    <br>
  </div>
</body>
</html>
```

**Comment by dhowe** [comment]
I also notice that a cookie is being stripped just before the visit...

**Comment by dhowe** [comment]
Here is a test case: http://lab-lamp.scm.cityu.edu.hk/adntest/redirect-notice.html

**Comment by cqx931** [comment]
> https://www.googleadservices.com/pagead/aclk?sa=L&ai=CcgZ5H1t4WPWXDoTr2AS8wKDAA7K4ibhHssiNvaIE3tkeEAEggcHwIWDZAqABuqXixQPIAQOpAslZqb8darQ-qAMByAPJBKoEqwFP0NXfqbc0BkadcqEDC_dkcwcheoaOd8DvI5drTkDFGOICKStSfL3uqRA39WAkQkWOjJu49QqHtVEr8w4K8pBzkJRXBKGqZ0TUx4sPKiTLk169bhbfAeSSIm1wckGZcYhkBS39TqB3sSnyW-fpv_ITdTmsLu73PI3OsPcXnWRJEpijzRdL4BzFQAabLRzsyjLUw9Sglad4fFky8-Sr-OSchBjiM_KBBit2ndiIBgGgBgOAB67anTqoB6a-G9gHAdIIBQiAYRAB&num=1&cid=CAASEuRoryuBheat7Ykox4VEn7LMXA&sig=AOD64_3P1GDoltxhUSbvGhmsGvmWHgYVBg&client=ca-pub-0160058262814943&nm=1&nx=238&ny=36&mb=2&bg=!PT6lPiZE3FtPGOSNA78CAAAAV1IAAAAOmQGGdvZBoSjm4T1Z14e1Q1HHTmwJEQ_UieZ-BFWz5NMJ7Rk6irhJwZvxVUy5CSVoJtPiTqv5uS3vUc7NJImpJeIxr20EV0kSii0CL_dIvi5WHcr6cgKhOHydsxJx4bRqH2EEF-07VaKAqeeEadzNtEJ6_NCmmcxqTvji_Anxz6MdCBS4ffNhHENdFUFrpcrU9HVZ8PJ7EdlE_8C9t5dkJlMNa4Z5Ew_yY-iM8OT_L6eunVlViGybIFOhG_7TiKc9ddiOAylvusVsk-AHswSiDU-3TOk9m3tcowAw-ZBxPrLZsJPBBqNTczoO3dycxULHP_yeIsszg_2VGevGohiEIgA5JDnjqV_5ahnTllgIyLDMrk2T5U3Z_N6YDR1lt8t6QMFzHylx8GdAPrH9PYhPKNd9m6UVkR1yhiZDhgeDhtFvxjwApBn_MIozzPDO1fHkD7qcbN7iFe92ZPDLsedwRwoFnK-GyO3W1qDPwyumcxCYDFOK1PpB8_J3BLC0m5HK0CNeJJZtMKEK&adurl=http://www.sevencapital.com/development/madison-house/

Above is the target Url link that I copy pasted from the ad(right click, copy link address). If I click it , it redirect me directly to the target page.

In adnauseam,the target url was fetched from "data-original-click-url" from this commit https://github.com/dhowe/AdNauseam/commit/ed0a0c944de2b94e61213b4efb593183e582b3fb. However, this address is not the exact same one of the unfolded link. Instead of seamless redirect, it landed in a redirect notice page, which results in the redirect notice title.

> https://www.googleadservices.com/pagead/aclk?sa=L&ai=CcgZ5H1t4WPWXDoTr2AS8wKDAA7K4ibhHssiNvaIE3tkeEAEggcHwIWDZAqABuqXixQPIAQOpAslZqb8darQ-qAMByAPJBKoEqwFP0NXfqbc0BkadcqEDC_dkcwcheoaOd8DvI5drTkDFGOICKStSfL3uqRA39WAkQkWOjJu49QqHtVEr8w4K8pBzkJRXBKGqZ0TUx4sPKiTLk169bhbfAeSSIm1wckGZcYhkBS39TqB3sSnyW-fpv_ITdTmsLu73PI3OsPcXnWRJEpijzRdL4BzFQAabLRzsyjLUw9Sglad4fFky8-Sr-OSchBjiM_KBBit2ndiIBgGgBgOAB67anTqoB6a-G9gHAdIIBQiAYRAB&num=1&cid=CAASEuRoryuBheat7Ykox4VEn7LMXA&sig=AOD64_3P1GDoltxhUSbvGhmsGvmWHgYVBg&client=ca-pub-0160058262814943&adurl=http://www.sevencapital.com/development/madison-house

so apparently this part of the url is missing:
> &nm=1&nx=238&ny=36&mb=2&bg=!PT6lPiZE3FtPGOSNA78CAAAAV1IAAAAOmQGGdvZBoSjm4T1Z14e1Q1HHTmwJEQ_UieZ-BFWz5NMJ7Rk6irhJwZvxVUy5CSVoJtPiTqv5uS3vUc7NJImpJeIxr20EV0kSii0CL_dIvi5WHcr6cgKhOHydsxJx4bRqH2EEF-07VaKAqeeEadzNtEJ6_NCmmcxqTvji_Anxz6MdCBS4ffNhHENdFUFrpcrU9HVZ8PJ7EdlE_8C9t5dkJlMNa4Z5Ew_yY-iM8OT_L6eunVlViGybIFOhG_7TiKc9ddiOAylvusVsk-AHswSiDU-3TOk9m3tcowAw-ZBxPrLZsJPBBqNTczoO3dycxULHP_yeIsszg_2VGevGohiEIgA5JDnjqV_5ahnTllgIyLDMrk2T5U3Z_N6YDR1lt8t6QMFzHylx8GdAPrH9PYhPKNd9m6UVkR1yhiZDhgeDhtFvxjwApBn_MIozzPDO1fHkD7qcbN7iFe92ZPDLsedwRwoFnK-GyO3W1qDPwyumcxCYDFOK1PpB8_J3BLC0m5HK0CNeJJZtMKEK

So to solve this problem, we still need to find another way to get the real href and also pay attention to the case without domain name:
https://github.com/dhowe/AdNauseam/issues/736

**Comment by cqx931** [comment]
Also, it is better to use console.dir to log the url, as console.log will shorten the url and it is not the real url in the variable.

http://stackoverflow.com/questions/19184313/disable-url-shortening-formatting-in-chromes-console

**Comment by cqx931** [comment]
This issue still exist when the correct href is collected by AdNauseam.
With the same link, the response page adnauseam received from the xhr request is still the "redirect notice", with a status of 200.
![image](https://cloud.githubusercontent.com/assets/3056154/22136308/adc2ac58-df0e-11e6-9336-fbdfadd38151.png)

But if I click the link in the browser,  the server seems to response with a 302 first and then redirect me to the final page.
![image](https://cloud.githubusercontent.com/assets/3056154/22136189/f4884824-df0d-11e6-9c6c-422f28a9a66a.png)

**Comment by cqx931** [comment]
So with the correct url collected, the issue still exist.
This time, the problem lies in https://github.com/dhowe/AdNauseam/blob/master/src/js/adn/core.js#L627

So even if the parser pick the same url as the href, the only different of the request made is that the real href ends with a "/", and adnauseam trim that part off before all ad visit and also won't save it in json.

So for the one with "/", the server response with 302 and the page get seamless redirection.
Whereas the one without "/", the server response with the redirect page.

https://www.googleadservices.com/pagead/aclk?sa=L&ai=CcgZ5H1t4WPWXDoTr2AS8wKDAA7K4ibhHssiNvaIE3tkeEAEggcHwIWDZAqABuqXixQPIAQOpAslZqb8darQ-qAMByAPJBKoEqwFP0NXfqbc0BkadcqEDC_dkcwcheoaOd8DvI5drTkDFGOICKStSfL3uqRA39WAkQkWOjJu49QqHtVEr8w4K8pBzkJRXBKGqZ0TUx4sPKiTLk169bhbfAeSSIm1wckGZcYhkBS39TqB3sSnyW-fpv_ITdTmsLu73PI3OsPcXnWRJEpijzRdL4BzFQAabLRzsyjLUw9Sglad4fFky8-Sr-OSchBjiM_KBBit2ndiIBgGgBgOAB67anTqoB6a-G9gHAdIIBQiAYRAB&num=1&cid=CAASEuRoryuBheat7Ykox4VEn7LMXA&sig=AOD64_3P1GDoltxhUSbvGhmsGvmWHgYVBg&client=ca-pub-0160058262814943&nm=1&nx=238&ny=36&mb=2&bg=!PT6lPiZE3FtPGOSNA78CAAAAV1IAAAAOmQGGdvZBoSjm4T1Z14e1Q1HHTmwJEQ_UieZ-BFWz5NMJ7Rk6irhJwZvxVUy5CSVoJtPiTqv5uS3vUc7NJImpJeIxr20EV0kSii0CL_dIvi5WHcr6cgKhOHydsxJx4bRqH2EEF-07VaKAqeeEadzNtEJ6_NCmmcxqTvji_Anxz6MdCBS4ffNhHENdFUFrpcrU9HVZ8PJ7EdlE_8C9t5dkJlMNa4Z5Ew_yY-iM8OT_L6eunVlViGybIFOhG_7TiKc9ddiOAylvusVsk-AHswSiDU-3TOk9m3tcowAw-ZBxPrLZsJPBBqNTczoO3dycxULHP_yeIsszg_2VGevGohiEIgA5JDnjqV_5ahnTllgIyLDMrk2T5U3Z_N6YDR1lt8t6QMFzHylx8GdAPrH9PYhPKNd9m6UVkR1yhiZDhgeDhtFvxjwApBn_MIozzPDO1fHkD7qcbN7iFe92ZPDLsedwRwoFnK-GyO3W1qDPwyumcxCYDFOK1PpB8_J3BLC0m5HK0CNeJJZtMKEK&adurl=http://www.sevencapital.com/development/madison-house

https://www.googleadservices.com/pagead/aclk?sa=L&ai=CcgZ5H1t4WPWXDoTr2AS8wKDAA7K4ibhHssiNvaIE3tkeEAEggcHwIWDZAqABuqXixQPIAQOpAslZqb8darQ-qAMByAPJBKoEqwFP0NXfqbc0BkadcqEDC_dkcwcheoaOd8DvI5drTkDFGOICKStSfL3uqRA39WAkQkWOjJu49QqHtVEr8w4K8pBzkJRXBKGqZ0TUx4sPKiTLk169bhbfAeSSIm1wckGZcYhkBS39TqB3sSnyW-fpv_ITdTmsLu73PI3OsPcXnWRJEpijzRdL4BzFQAabLRzsyjLUw9Sglad4fFky8-Sr-OSchBjiM_KBBit2ndiIBgGgBgOAB67anTqoB6a-G9gHAdIIBQiAYRAB&num=1&cid=CAASEuRoryuBheat7Ykox4VEn7LMXA&sig=AOD64_3P1GDoltxhUSbvGhmsGvmWHgYVBg&client=ca-pub-0160058262814943&nm=1&nx=238&ny=36&mb=2&bg=!PT6lPiZE3FtPGOSNA78CAAAAV1IAAAAOmQGGdvZBoSjm4T1Z14e1Q1HHTmwJEQ_UieZ-BFWz5NMJ7Rk6irhJwZvxVUy5CSVoJtPiTqv5uS3vUc7NJImpJeIxr20EV0kSii0CL_dIvi5WHcr6cgKhOHydsxJx4bRqH2EEF-07VaKAqeeEadzNtEJ6_NCmmcxqTvji_Anxz6MdCBS4ffNhHENdFUFrpcrU9HVZ8PJ7EdlE_8C9t5dkJlMNa4Z5Ew_yY-iM8OT_L6eunVlViGybIFOhG_7TiKc9ddiOAylvusVsk-AHswSiDU-3TOk9m3tcowAw-ZBxPrLZsJPBBqNTczoO3dycxULHP_yeIsszg_2VGevGohiEIgA5JDnjqV_5ahnTllgIyLDMrk2T5U3Z_N6YDR1lt8t6QMFzHylx8GdAPrH9PYhPKNd9m6UVkR1yhiZDhgeDhtFvxjwApBn_MIozzPDO1fHkD7qcbN7iFe92ZPDLsedwRwoFnK-GyO3W1qDPwyumcxCYDFOK1PpB8_J3BLC0m5HK0CNeJJZtMKEK&adurl=http://www.sevencapital.com/development/madison-house/

**Comment by dhowe** [comment]
I remember there was a reason for this, but I'm not sure what it was
in any case, why don't you comment it, then we can watch for any problems

**Comment by cqx931** [comment]
https://github.com/dhowe/AdNauseam/pull/779

**Comment by cqx931** [comment]
close for now
