### ISSUE TITLE
"Adnauseam filters" breaks various google domains.

### ISSUE THREAD

**Issue by PriceChild** [dhowe/AdNauseam#769]
With "AdNauseam filters‎" checked in AdNauseam's "3rd party filters" tab, various google properties are breaking for me.

The easiest to notice is inbox.google.com where most images don't load.

I've also seen 2FA fail on accounts.google.com.

Disabling the list fixes these for me.

**Comment by dhowe** [comment]
Confirmed -- working on a fix now...

**Comment by cqx931** [comment]
To test, please update adnauseam.txt with the following steps:
Go to Settings->3rd-party-filters, 'purge-all-caches', 'apply', then click 'update now'.

**Comment by PriceChild** [comment]
Looks much better, thanks.

**Comment by PriceChild** [comment]
Apologies for what's likely a silly question (and I did check [the faq](https://github.com/dhowe/adnauseam/wiki/FAQ)) but I was wondering why Adnauseam maintains its own list?

I've just found https://github.com/dhowe/uAssets/blob/master/README.md So is it really because the maintainers of the default lists you include are a little too slow fixing issues, and you aim to do it here instead?

**Comment by dhowe** [comment]
Being able to update our lists immediately is nice (as in the above case), but another reason is that our requirements are a bit different from uBlock (on which AdNauseam is built); specifically, there are certain requests we need to allow, in order to collect as many ads as possible; and also cases where we need additional rules to make sure we get all the ad data needed... thus we use our own list for this

**Comment by mneunomne** [comment]
Seems this is fixed, closing.
