### ISSUE TITLE
Tests on branch 'merged-1.9.10'

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#780]
Pls do a quick run through the test set on branch 'merged-1.9.10'

If it all looks good, I will go ahead with the next set of merges...

**Comment by cqx931** [comment]
First-Run

- [ ] Remove and reinstall AdNauseam to trigger this page
- [ ] Test selection of various options (click-ads, block-malware, hide-ads, DNT)
- [ ] Verify that the DNT option is visible only when clicking OR hiding is enabled
- [ ] Test that toggling the DNT option changes both DNT options in Settings
- [ ] Check the links on first-run page
- [ ] Check the version number at left-bottom corner

Menu
- [ ] Check all buttons and information (including number of Ads and $$ cost, hidden if no ads)
- [ ] Hover over Ad images and check zooming
- [ ] Check there is no text overlap in the menu for text ads
- [ ] Check the uBlock version number(in uBlock menu)

Vault
- [ ] Verify loading animation, and centering/scaling of Ads on load
- [ ] Zoom in/out using mouse wheel and buttons in top-left corner
- [ ] Check function/layout of Inspector (for both image and text ads)
- [ ] Check correct function of date-filter slider at bottom
- [ ] Check that AdNauseam logo in the bottom-right corner links correctly to homepage
- [ ] Check correct calculation of ad cost (and $$$ updates according to date-filter, hidden if no ads)
- [ ] Test import/export/clear functions

Dashboard
- [ ] Check 2 version numbers in 'About' page (links.html)
- [ ] Check layout of buttons, check-boxes, and links in each tab
- [ ] Test that all (i)nfo buttons lead to correct FAQ pages in each tab
- [ ] On settings tab (options.html) check that when clicking or hiding are disabled, then all of their sub-items are also disabled
- [ ] Test import/export/clear ads functions
- [ ] Test whitelist

Toolbar Icon
- [ ] Check that the icon in the toolbar is in purple when AdNauseam is active
- [ ] Check that the icon in the toolbar is in grey when AdNauseam is disabled
- [ ] Check that the icon in the toolbar is in green when on DNT pages
- [ ] Icon should animate each time an Ad is clicked (>= v3.1)

 Notifications
- [ ] Check that disabling hiding, clicking, or blocking on the first-run generates a notification warning at the top of the dashboard (all tabs), menu, and vault page (after first-run is closed or 'ok' is clicked).
- [ ] Check that disabling hiding, clicking, or blocking on the dashboard/options page generates a notification warning at the top of the dashboard(all tabs), menu, and vault page.
- [ ] Check that disabling EasyList on the dashboard/3p-filters page generates a notification warning at the top of the dashboard(all tabs), menu, and vault page.
- [ ] Check that clicking 'reactivate' on a notification warning at the top of the dashboard, menu, or vault pages causes the visual state to change correctly, and the setting in question to be updated correctly.
- [ ] Check that the vault (if open) is updated when notifications change
- [ ] Check that the dashboard (if open) is updated when notifications change
- [ ] Dashboard::settings (options.html) Check that page refreshes correctly when a notification is 'reactivated'
- [ ] Dashboard::3rd-Party (3p-filters.html) Check that page refreshes correctly when a list-notification is 'reactivated'

Ad Hiding/Parsing
- [ ] Test a set of pages, and make sure that ads are being captured and visited
- [ ] ImageAds: visit Facebook/Youtube/Amazon... and verify ads are hidden and appear in menu
- [ ] TextAds: visit Google/Ask/Yahoo/Bing/DuckDuckGo to search for keywords such as "credit card" or "loan"
- [ ] Test Ad-parsing from within dynamically-created iFrames here
- [ ] Test Ad-parsing from cosmetically filtered iFrames (without cosmetic filters for any contained elements) here
- [ ] Test that no Ads are collected in incognito/private-browsing windows:
- [ ] In Chrome/Opera, go to the extension page and check "Allow in incognito" for AdNauseam, then hit command+shift+N to start testing
- [ ] In Firefox, use command+shift+P to open a private window

DoNotTrack (DNT)
- [ ] DNT: Go to a DNT page (Ex: duckduckgo.com) and check the following items:
- [ ] 
- [ ]     Headers/Cookies
- [ ] 
- [ ]     To check ad visits headers, click on request in browser's network panel, select 'Headers'     (For a more detailed network logging, you can check Chrome Net-Internals of the tools listed below.)
- [ ] 
- [ ] DNT-header is being sent correctly for ALL requests (including Ad visits) if either disableClickingForDNT and disableHidingForDNT are enabled (and vice versa)
- [ ] DNT Cookie handling (v3.1 and later)

 Hiding/Clicking
- [ ] Ads are visible when domain is 1st-party iff disableHidingForDNT is checked
- [ ] Requests are not blocked when domain is 1st-party iff disableHidingForDNT is checked
- [ ] Requests are not blocked when domain is 3rd-party iff disableHidingForDNT is checked
- [ ] No clicking when ad domain is on list iff disableClickingForDNT is checked (especially for 3rd-party)
- [ ] If both DNT options are disabled, then hiding, blocking, visiting occur again as usual

Interface
- [ ] DNT list at top of whitelist.html is checked when either DNT option is checked, otherwise unchecked
- [ ] Check that changing the two DNT settings will triggger DNT notifications with corresponding messages to the menu
- [ ] Check the layout of each DNT notification("?" should be in the middle, 'settings' button appears on hover)
- [ ]     Test Page for 3rd-party DNT

- [ ] Cookies
- [ ] Test that no cookies are accepted from adn-ALLOWed requests:
- [ ] Make sure ‘Activate debugging mode’ is set to true to view log info in the console
- [ ] Visit sites where one or more 3rd-party requests are adn-ALLOWed and note their domains
- [ ] Verify that no cookies are accepted from these domains: first by checking cookies before/after in the browser, then verify using one of the tools listed below (look for 'set-cookies' in response Header)

Ad Visits
- [ ] To check headers for ad visits, please go to developer tools of the browser -> Network -> click on a request -> select 'Headers'. You can also click on 'XHR' type to filter the requests. (For a more detailed network logging, you can check Chrome Net-Internals of the tools listed below.)
- [ ] 
- [ ] Test that the correct 'referer' header is sent on Ad visits depending on the setting (ad.pageUrl when disabled, or none when enabled)
- [ ] Test that the correct 'user-agent' header is sent on Ad visits depending on the setting (the usual user-agent when disabled, or default when enabled)
- [ ] Test that outgoing cookies are sent on Ad visits depending on the setting (the usual cookies when disabled, or none when enabled)
- [ ] Test that incoming cookies are not allowed from responses to Ad visits, by checking cookies before/after (if only Channel ID cookies are allowed, it is ok for now)

Check Ad Blockers
- [ ] Install uBlock
- [ ] Remove and reinstall AdNauseam to trigger the first-run page
- [ ] check if there is a warning about other ad blockers on first-run page,menu and vault
- [ ] click 'disable' button on the warning message, it should lead to the extension page
- [ ] disable uBlock and check whether the message is gone in vault and menu.(If the page was opened, it need to be refreshed)
- [ ] Test this for only AdBlock Plus installed, only uBlock/uBlock Origin, and both installed

- [ ] Check Blocking
- [ ] Check that the request from the following test page is blocked by adnauseam by using the uBlock logger. here

**Comment by cqx931** [comment]
All good. The text-ad issue https://github.com/dhowe/AdNauseam/issues/781 is not related to the new merge.

**Comment by dhowe** [comment]
Good
