### ISSUE TITLE
Null tab in click animation

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#783]
```
Null tab in click animation!
warn @ core.js:831
(anonymous) @ core.js:430
onTabReceived @ vapi-background.js:377
target.(anonymous function) @ extensions::SafeBuiltins:19
safeCallbackApply @ extensions::sendRequest:21
handleResponse @ extensions::sendRequest:74

```

**Comment by cqx931** [comment]
What vAPI.tabs.get(null) tries to do is to get the active tab in the current window. It returns null only when a separate console becomes the current window, because there is no tab in it.
As long as the focus is on the window where the page tab is rather than a separate console window, this works fine.

**Comment by dhowe** [comment]
pls make the change

**Comment by cqx931** [comment]
https://github.com/dhowe/AdNauseam/pull/817/commits/9ef7a52710922b44e2a46e943e547ee7578b075c fixed
