### ISSUE TITLE
Bug: Toggle AdNauseam appears

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#930]
To recreate:

1. Visit http://www.greatfirewallofchina.org/index.php?siteurl=rednoise.org
2. Open menu and leave open
3. Mouse over top-left corner 

(can't get screenshot)

**Comment by cqx931** [comment]
Only see this in Chrome. Opera and Firefox are ok.

**Comment by cqx931** [comment]
https://github.com/dhowe/AdNauseam/pull/934/commits/39a709212fafb29fdeced05b3297761b63d03b8b
This should be related to how chrome handles title attribute.
From my observation, chrome seems to show title hover text with a few seconds delay on hover, and the text only disappears on mouse out. 
In our menu layout there used to be no gaps between the element that contains the title and the menu window. If the user hover on the logo and move the mouse to the main window without leaving the icon area, chrome will consider the mouse still hover on the icon and display the hover text.

I have adjusted the icon div so that there is a 10px margin on top and right hand side, so that the mouse out event could be triggered successfully.
