### ISSUE TITLE
Crunchyroll video ads not being blocked

### ISSUE THREAD

**Issue by 2c2c** [dhowe/AdNauseam#971]
These were being blocked on ublock. I'm using chrome.

http://www.crunchyroll.com/dragon-ball-super/episode-85-the-universes-begin-to-make-their-moves-their-individual-motives-733117

**Comment by cqx931** [comment]
Thank you for reporting the issue, it should be fixed by now.
Please verify by updating the latest AdNauseam filter:

1.Go to AdNauseam Settings page (from Menu), then open the 3rd-party-filters panel
2.For AdNauseam v3.3.32, click 'update' button for AdNauseam filters; For any earlier version, click 'purge-all-caches' - 'apply changes' - 'update now'
3.Reload the page on which you saw the problem

**Comment by greysonevins** [comment]
It  looks like the video ads are blocked by v3.3.32 like @cqx931 mentioned. I cannot duplicate the issue.

**Comment by cqx931** [comment]
fixed, close
