### ISSUE TITLE
Ads not collected on stackoverflow.com

### ISSUE THREAD

**Issue by greysonevins** [dhowe/AdNauseam#985]
### Describe the issue

2 ads hidden but not collected

### One or more specific URLs where the issue occurs
http://stackoverflow.com/questions/22876978/loop-inside-react-jsx

### Screenshot in which the issue can be seen

![image](https://cloud.githubusercontent.com/assets/11656811/25055827/25413c8e-2133-11e7-95bc-7b9e8568f24f.png)

**Comment by greysonevins** [comment]
The two Ads I mentioned were a fault on my end. Needed to clear cache, etc.

However there are two dynamic ads that use location and search data to advertise jobs. I am working on it not.

Found under the divs `###hireme` and `##clc-cp-sb`
![image](https://cloud.githubusercontent.com/assets/11656811/25059835/1ac24374-215c-11e7-8ac0-f7051252cf56.png)

![image](https://cloud.githubusercontent.com/assets/11656811/25059840/406ae626-215c-11e7-8fa4-d591ea37053a.png)

Part of the issue is that ublock prevents the javascript from loading and the ad link is connected to the same url:
`||clc.stackoverflow.com/`

Still working on it.

**Comment by cqx931** [comment]
"Jobs near you" won't be collected because it is a text ad and currently we don't have stack overflow in our text parser, For the sites we support text ads, please [see](https://github.com/dhowe/AdNauseam/blob/master/src/js/adn/textads.js#L330)  (mainly from search result)
I can't get the second one, but it also seems to be a dynamic ad to me (see below).

At this stage AdNauseam only collects:
1. Image Ad(Single Image wrapped with <a> tag)
2.Text Ad from search result page

What AdNauseam only blocks and doesn't collect:
1.Video Ad
2.Audio Ad
3.Dynamic Ad(Animated ad consists of many tiny images / text & images/ dom elements)
4.Background Images

**Comment by dhowe** [comment]
Here is another (linking to http://engine.adzerk.net/...):

![image](https://cloud.githubusercontent.com/assets/737638/25060142/c6ac7b20-21c8-11e7-9a6a-f03f191df3d8.png)

**Comment by greysonevins** [comment]
@dhowe How should I move forward with this one?

**Comment by dhowe** [comment]
recheck stackoverflow for any ads

**Comment by cqx931** [comment]
Please check: https://github.com/dhowe/uAssets/pull/73
Now the two image ads should be collected by adnauseam.
